local Assert = require("tests.assert")
local Actions = require("kiwi.terminal.actions")
local Parser = require("kiwi.terminal.parser")
local Snapshot = require("kiwi.terminal.snapshot")
local State = require("kiwi.terminal.state")

local function marker(state, value)
  state:apply(Actions.osc(133, value))
end

return {
  command_regions_model_prompt_command_output_and_completion = function()
    local state = State.new(20, 3)
    Parser.new(state):feed("\27]7;file://host.example/work\7\27]133;A\7P> \27]133;B\7run\27]133;C\7\r\nout\r\n\27]133;D;7\7")
    local view = state.command_regions:view()
    local region = view.regions[1]
    Assert.equal(#view.regions, 1)
    Assert.equal(view.active_id, nil)
    Assert.equal(region.id, 1)
    Assert.equal(region.cwd_id, 1)
    Assert.equal(region.scope, "primary")
    Assert.equal(region.state, "completed")
    Assert.equal(region.prompt_start.column, 0)
    Assert.equal(region.command_start.column, 3)
    Assert.equal(region.output_start.column, 6)
    Assert.equal(region.finish.line_id, state.active_screen.rows[2].line_id)
    Assert.equal(region.exit_status, 7)
    Assert.equal(region.recovery, nil)
  end,

  command_regions_recover_missing_out_of_order_and_repeated_markers = function()
    local state = State.new(4, 1)
    marker(state, "B")
    marker(state, "C")
    marker(state, "C")
    marker(state, "B")
    marker(state, "D;4")
    marker(state, "D")
    local view = state.command_regions:view()
    Assert.equal(#view.regions, 2)
    Assert.equal(view.regions[1].state, "interrupted")
    Assert.equal(view.regions[1].interruption, "next-command")
    Assert.equal(view.regions[2].state, "completed")
    Assert.equal(view.regions[2].recovery[1], "missing-prompt")
    Assert.equal(view.regions[2].recovery[2], "missing-command-executed")
    Assert.equal(view.regions[2].exit_status, 4)
    Assert.equal(view.stats.recovered, 3)
    Assert.equal(view.stats.repeated, 1)
    Assert.equal(view.stats.interrupted, 1)
    Assert.equal(view.stats.orphaned, 1)
  end,

  command_regions_keep_scopes_stable_and_bound_historical_metadata = function()
    local state = State.new(4, 1, { command_regions = { limit = 1 } })
    marker(state, "A")
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    marker(state, "C")
    marker(state, "D;0")
    local view = state.command_regions:view()
    Assert.equal(#view.regions, 1)
    Assert.equal(view.regions[1].id, 2)
    Assert.equal(view.regions[1].scope, "alternate")
    Assert.equal(view.regions[1].state, "completed")
    Assert.equal(view.stats.interrupted, 1)
    Assert.equal(view.stats.dropped, 1)
    Assert.equal(view.stats.recovered, 1)
    Assert.equal(Snapshot.encode(state):find("host%.example"), nil)
    state:reset()
    Assert.equal(#state.command_regions:view().regions, 0)
    Assert.equal(state.command_regions:view().active_id, nil)
  end,
}
