local Assert = require("tests.assert")
local HarfBuzz = require("kiwi.text.harfbuzz")
local Layout = require("kiwi.text.layout")
local State = require("kiwi.terminal.state")
local System = require("kiwi.font.system")
local Utf8 = require("kiwi.terminal.utf8")

local function write(state, codepoint)
  state:write_codepoint(Utf8.encode(codepoint), codepoint)
end

local function text_system()
  return System.new({ pixel_height = 18, atlas = { width = 512, height = 512, max_entries = 1024 } })
end

return {
  harfbuzz_shapes_real_freetype_faces_with_monotone_grapheme_clusters = function()
    local system = text_system()
    local glyphs = system.primary:shape("e" .. Utf8.encode(0x0301), { ligatures = false, contextual_alternates = false })
    Assert.truthy(#HarfBuzz.version() > 0)
    Assert.truthy(#glyphs >= 1)
    Assert.equal(glyphs[1].cluster, 0)
    Assert.truthy(glyphs[1].glyph_id > 0)
    system:destroy()
  end,
  font_system_resolves_and_caches_cjk_fallbacks = function()
    local system = text_system()
    local primary = assert(system:face_for_cluster({ string.byte("A") }))
    local cjk = assert(system:face_for_cluster({ 0x4e2d }))
    Assert.truthy(primary.id ~= cjk.id)
    local repeated = assert(system:face_for_cluster({ 0x4e2d }))
    Assert.equal(repeated, cjk)
    Assert.truthy(system.stats.fallback_hits >= 2)
    system:destroy()
  end,
  dynamic_glyph_cache_keys_by_face_and_glyph_id_and_bounds_growth = function()
    local system = text_system()
    local primary = assert(system:face_for_cluster({ string.byte("A") }))
    local glyph = assert(system.glyph_cache:get_or_insert(primary, primary:glyph_index(string.byte("A"))))
    local repeated = assert(system.glyph_cache:get_or_insert(primary, primary:glyph_index(string.byte("A"))))
    Assert.equal(repeated, glyph)
    Assert.equal(system.glyph_cache.stats.hits, 1)
    Assert.equal(system.glyph_cache.atlas:glyph_count(), 1)
    system:destroy()
  end,
  text_caches_bound_atlas_growth_and_negative_fallback_lookups = function()
    local system = System.new({ pixel_height = 18, atlas = { width = 512, height = 512, max_entries = 2 } })
    local face = assert(system:face_for_cluster({ string.byte("A") }))
    assert(system.glyph_cache:get_or_insert(face, face:glyph_index(string.byte("A"))))
    assert(system.glyph_cache:get_or_insert(face, face:glyph_index(string.byte("B"))))
    local third, reason = system.glyph_cache:get_or_insert(face, face:glyph_index(string.byte("C")))
    Assert.equal(third, nil)
    Assert.equal(reason, "entry-limit")
    Assert.equal(system:face_for_cluster({ 0x10ffff }), nil)
    Assert.equal(system:face_for_cluster({ 0x10ffff }), nil)
    Assert.equal(system.stats.fallback_misses, 1)
    Assert.equal(system.stats.negative_fallback_hits, 1)
    system:destroy()
  end,
  text_layout_reuses_static_rows_and_keeps_logical_damage_separate = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(8, 2)
    write(state, string.byte("e"))
    write(state, 0x0301)
    write(state, 0x4e2d)
    local initial = layout:update(state)
    Assert.truthy(#initial >= 2)
    Assert.equal(layout.stats.rows_reshaped, 2)
    state.damage:clear()
    local static = layout:update(state)
    Assert.equal(#static, #initial)
    Assert.equal(layout.stats.rows_reshaped, 0)
    Assert.equal(layout.stats.cache_hits, 2)
    write(state, string.byte("A"))
    local changed = layout:update(state)
    Assert.truthy(#changed >= #initial)
    Assert.equal(layout.stats.rows_reshaped, 1)
    Assert.equal(layout.stats.rows_invalidated, 1)
    system:destroy()
  end,
}
