local Assert = require("tests.assert")
local Actions = require("kiwi.terminal.actions")
local HarfBuzz = require("kiwi.text.harfbuzz")
local Inspector = require("kiwi.diagnostics.text_inspector")
local Layout = require("kiwi.text.layout")
local Parser = require("kiwi.terminal.parser")
local State = require("kiwi.terminal.state")
local System = require("kiwi.font.system")
local Utf8 = require("kiwi.terminal.utf8")

local function write(state, codepoint)
  state:write_codepoint(Utf8.encode(codepoint), codepoint)
end

local function text_system()
  return System.new({ pixel_height = 18, atlas = { width = 512, height = 512, max_entries = 1024 } })
end

return {
  harfbuzz_shapes_real_freetype_faces_with_monotone_grapheme_clusters = function()
    local system = text_system()
    local glyphs = system.primary:shape("e" .. Utf8.encode(0x0301), { ligatures = false, contextual_alternates = false })
    Assert.truthy(#HarfBuzz.version() > 0)
    Assert.truthy(#glyphs >= 1)
    Assert.equal(glyphs[1].cluster, 0)
    Assert.truthy(glyphs[1].glyph_id > 0)
    system:destroy()
  end,
  font_system_resolves_and_caches_cjk_fallbacks = function()
    local system = text_system()
    local primary = assert(system:face_for_cluster({ string.byte("A") }))
    local cjk = assert(system:face_for_cluster({ 0x4e2d }))
    Assert.truthy(primary.id ~= cjk.id)
    local repeated = assert(system:face_for_cluster({ 0x4e2d }))
    Assert.equal(repeated, cjk)
    Assert.truthy(system.stats.fallback_hits >= 2)
    system:destroy()
  end,
  font_system_caches_primary_ascii_coverage_without_changing_face_selection = function()
    local system = text_system()
    local first = assert(system:face_for_cluster({ string.byte("A") }))
    local repeated = assert(system:face_for_cluster({ string.byte("A") }))
    Assert.equal(first, system.primary)
    Assert.equal(repeated, system.primary)
    Assert.equal(system.stats.primary_ascii_coverage_probes, 1)
    Assert.equal(system.stats.primary_ascii_cache_hits, 1)
    Assert.equal(system.stats.fallback_hits, 0)
    system:destroy()
  end,
  text_layout_shapes_documented_cjk_categories_with_fallback_faces = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(12, 1)
    for _, codepoint in ipairs({ 0x4e2d, 0x3042, 0x30ab, 0xd55c, 0xff01, 0xff76 }) do write(state, codepoint) end
    local glyphs = layout:update(state)
    Assert.equal(state:get(0, 0).width, 2)
    Assert.equal(state:get(10, 0).width, 1)
    Assert.truthy(#glyphs >= 6)
    Assert.truthy(system.stats.fallback_hits >= 5)
    system:destroy()
  end,
  text_layout_renders_transient_ime_preedit_without_mutating_terminal_cells = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(8, 1)
    state.ime_preedit = { column = 2, row = 0, text = "中" }
    local glyphs = layout:update(state)
    Assert.truthy(#glyphs >= 1)
    Assert.equal(state:get(2, 0).glyph, " ")
    Assert.equal(glyphs[1].cluster_column, 2)
    Assert.equal(glyphs[1].flags % 64 >= 32, true)
    state.ime_preedit = nil
    Assert.equal(#layout:update(state), 0)
    system:destroy()
  end,
  text_layout_applies_reverse_screen_video_without_rewriting_cells = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(4, 1)
    state:write_codepoint("A")
    local initial = layout:update(state)
    Assert.truthy(#initial >= 1)
    local cell = state:get(0, 0)
    Assert.equal(initial[1].fg, cell.fg)
    Parser.new(state):feed("\27[?5h")
    local reversed = layout:update(state)
    Assert.truthy(#reversed >= 1)
    Assert.equal(reversed[1].fg, cell.bg)
    Assert.equal(cell.fg, initial[1].fg)
    system:destroy()
  end,
  dynamic_glyph_cache_keys_by_face_and_glyph_id_and_bounds_growth = function()
    local system = text_system()
    local primary = assert(system:face_for_cluster({ string.byte("A") }))
    local glyph = assert(system.glyph_cache:get_or_insert(primary, primary:glyph_index(string.byte("A"))))
    local repeated = assert(system.glyph_cache:get_or_insert(primary, primary:glyph_index(string.byte("A"))))
    Assert.equal(repeated, glyph)
    Assert.equal(system.glyph_cache.stats.hits, 1)
    Assert.equal(system.glyph_cache.atlas:glyph_count(), 1)
    system:destroy()
  end,
  text_caches_bound_atlas_growth_and_negative_fallback_lookups = function()
    local system = System.new({ pixel_height = 18, atlas = { width = 512, height = 512, max_entries = 2 } })
    -- U+10FFFF may resolve to a platform Last Resort font, so make this cache test
    -- exercise a deterministic resolver miss rather than host font coverage.
    system.resolver.fallback = function() return nil end
    local face = assert(system:face_for_cluster({ string.byte("A") }))
    assert(system.glyph_cache:get_or_insert(face, face:glyph_index(string.byte("A"))))
    assert(system.glyph_cache:get_or_insert(face, face:glyph_index(string.byte("B"))))
    local third, reason = system.glyph_cache:get_or_insert(face, face:glyph_index(string.byte("C")))
    Assert.equal(third, nil)
    Assert.equal(reason, "entry-limit")
    local repeated, repeated_reason = system.glyph_cache:get_or_insert(face, face:glyph_index(string.byte("C")))
    Assert.equal(repeated, nil)
    Assert.equal(repeated_reason, "entry-limit")
    Assert.equal(system.glyph_cache.stats.negative_hits, 1)
    Assert.equal(system:face_for_cluster({ 0x10ffff }), nil)
    Assert.equal(system:face_for_cluster({ 0x10ffff }), nil)
    Assert.equal(system.stats.fallback_misses, 1)
    Assert.equal(system.stats.negative_fallback_hits, 1)
    system:destroy()
  end,
  text_degrades_to_a_missing_glyph_after_the_bounded_fallback_face_cache = function()
    local system = System.new({ pixel_height = 18, face_cache_limit = 1, atlas = { width = 512, height = 512, max_entries = 1024 } })
    local face, reason = system:face_for_cluster({ 0x4e2d })
    Assert.equal(face, nil)
    Assert.equal(reason, "missing")
    system:destroy()
  end,
  optional_nerd_font_private_use_glyph_uses_the_glyph_id_cache = function()
    local system = System.new({ pixel_height = 18, primary_family = "MartianMono Nerd Font", atlas = { width = 512, height = 512, max_entries = 1024 } })
    if not system.font_path:find("MartianMonoNerdFont", 1, true) then
      system:destroy()
      return
    end
    local face = assert(system:face_for_cluster({ 0xe0b0 }))
    local glyph_id = face:glyph_index(0xe0b0)
    Assert.truthy(glyph_id > 0)
    Assert.truthy(system.glyph_cache:get_or_insert(face, glyph_id) ~= nil)
    system:destroy()
  end,
  text_layout_reuses_static_rows_and_keeps_logical_damage_separate = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(8, 2)
    write(state, string.byte("e"))
    write(state, 0x0301)
    write(state, 0x4e2d)
    local initial = layout:update(state)
    Assert.truthy(#initial >= 2)
    Assert.equal(layout.stats.rows_reshaped, 2)
    Assert.truthy(layout.stats.visible_runs >= 1)
    Assert.equal(layout.stats.visible_glyphs, #initial)
    state.damage:clear()
    local static = layout:update(state)
    Assert.equal(#static, #initial)
    Assert.equal(layout.stats.rows_reshaped, 0)
    Assert.equal(layout.stats.cache_hits, 2)
    write(state, string.byte("A"))
    local changed = layout:update(state)
    Assert.truthy(#changed >= #initial)
    Assert.equal(layout.stats.rows_reshaped, 1)
    Assert.equal(layout.stats.rows_invalidated, 1)
    system:destroy()
  end,
  text_layout_ignores_cursor_and_sgr_only_damage_and_coalesces_text_rows = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(8, 2)
    write(state, string.byte("A"))
    layout:update(state)
    state.damage:clear()

    state:move_cursor(2, 1)
    Assert.truthy(state.damage:summary().cells > 0)
    Assert.equal(state.text_damage:summary().cells, 0)
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 0)

    state:apply(Actions.csi({ 31 }, "", "", "m"))
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 0)

    write(state, string.byte("B"))
    write(state, string.byte("C"))
    write(state, string.byte("D"))
    Assert.equal(state.text_damage:summary().ranges, 1)
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 1)
    system:destroy()
  end,
  text_layout_batches_an_ascii_burst_and_keeps_primary_glyphs_hot = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(80, 3, { text_counters = {} })
    layout:update(state)
    state.damage:clear()
    state.text_damage:clear()
    local parser = Parser.new(state)
    parser:feed(string.rep("A", 100))
    parser:finish()
    Assert.equal(state.text_counters.ascii_fast_path, 100)
    Assert.equal(state.text_counters.unicode_property_lookups or 0, 0)
    Assert.equal(state.text_counters.width_policy_calls or 0, 0)
    Assert.equal(state.text_damage:summary().ranges, 1)
    local fallback_before = system.stats.fallback_hits + system.stats.fallback_misses
    local misses_before = system.glyph_cache.stats.misses
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 2)
    Assert.equal(layout.stats.runs_reshaped, 2)
    Assert.equal(system.stats.fallback_hits + system.stats.fallback_misses, fallback_before)
    Assert.equal(system.glyph_cache.stats.misses - misses_before, 1)

    state:move_cursor(20, 2)
    write(state, string.byte("A"))
    misses_before = system.glyph_cache.stats.misses
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 1)
    Assert.equal(system.glyph_cache.stats.misses - misses_before, 0)
    system:destroy()
  end,
  text_layout_invalidates_on_shape_and_fallback_configuration_changes = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(8, 1)
    write(state, string.byte("f"))
    write(state, string.byte("i"))
    layout:update(state)
    state.damage:clear()
    Assert.truthy(system:set_shape_options({ ligatures = true, contextual_alternates = false }))
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 1)
    state.damage:clear()
    system:clear_fallback_cache()
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 1)
    system:destroy()
  end,
  text_layout_invalidates_on_font_replacement_resize_screen_switch_and_reset = function()
    local first = text_system()
    local layout = Layout.new(first)
    local state = State.new(8, 1)
    write(state, string.byte("A"))
    layout:update(state)
    state.damage:clear()

    local second = System.new({ pixel_height = 20, atlas = { width = 512, height = 512, max_entries = 1024 } })
    layout:set_font_system(second)
    first:destroy()
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 1)
    state.damage:clear()

    state:resize(8, 2)
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 2)
    state.damage:clear()

    state:switch_alternate(true, true)
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 2)
    state.damage:clear()

    state:reset()
    layout:update(state)
    Assert.equal(layout.stats.rows_reshaped, 2)
    second:destroy()
  end,
  text_inspector_exposes_shaped_glyph_mapping_for_an_anchor = function()
    local system = text_system()
    local layout = Layout.new(system)
    local state = State.new(4, 1)
    write(state, string.byte("A"))
    layout:update(state)
    local item = Inspector.describe(state, system, 0, 0, layout)
    Assert.equal(item.kind, "anchor")
    Assert.equal(#item.glyphs, 1)
    Assert.truthy(item.glyphs[1].glyph_id > 0)
    Assert.equal(item.glyphs[1].shape_cluster, 0)
    system:destroy()
  end,
}
