local Assert = require("tests.assert")
local Accessibility = require("kiwi.accessibility.model")
local State = require("kiwi.terminal.state")
local Utf8 = require("kiwi.terminal.utf8")

local function write(state, codepoint)
  state:write_codepoint(Utf8.encode(codepoint), codepoint)
end

return {
  accessibility_exports_grapheme_safe_visible_cells_and_caret = function()
    local state = State.new(8, 2)
    write(state, string.byte("A"))
    write(state, 0x4e2d)
    write(state, string.byte("e"))
    write(state, 0x0301)
    local model = Accessibility.new()
    local snapshot, events = model:poll(state)
    Assert.equal(events[1].kind, "initial")
    Assert.equal(snapshot.text.rows[1].text:sub(1, #("A中é")), "A中é")
    Assert.equal(snapshot.caret.column, 4)
    local range = model:range_at(state, 0, 2)
    Assert.equal(range.start_column, 1)
    Assert.equal(range.finish_column, 3)
    Assert.equal(range.text, "中")
  end,
  accessibility_bounds_visible_export_without_materializing_scrollback = function()
    local state = State.new(4, 2, { scrollback_limit = 32 })
    for codepoint = string.byte("A"), string.byte("F") do
      write(state, codepoint)
      state:line_feed()
    end
    state:scroll_history(2)
    local model = Accessibility.new({ max_rows = 1, max_bytes = 4 })
    local snapshot = model:snapshot(state)
    Assert.equal(snapshot.viewport.history_offset, 2)
    Assert.equal(snapshot.viewport.exported_rows, 1)
    Assert.equal(snapshot.viewport.omitted_rows, 1)
    Assert.equal(#snapshot.text.rows, 1)
    Assert.truthy(snapshot.text.rows[1].line_id > 0)
  end,
  accessibility_emits_deterministic_selection_resize_and_viewport_changes = function()
    local state = State.new(4, 2, { scrollback_limit = 8 })
    write(state, string.byte("A"))
    write(state, 0x4e2d)
    local model = Accessibility.new()
    model:poll(state)
    state:set_selection(0, 1, 0, 2)
    local _, selection_events = model:poll(state)
    Assert.equal(selection_events[1].kind, "selection")
    Assert.equal(selection_events[1].selection.start.column, 1)
    Assert.equal(selection_events[1].selection.finish.column, 3)
    state:resize(3, 1)
    local _, resize_events = model:poll(state)
    Assert.equal(resize_events[1].kind, "resize")
    write(state, string.byte("B"))
    state:line_feed()
    model:poll(state)
    state:scroll_history(1)
    local _, viewport_events = model:poll(state)
    Assert.equal(viewport_events[1].kind, "viewport")
  end,
}
