local Assert = require("tests.assert")
local State = require("kiwi.terminal.state")
local Utf8 = require("kiwi.terminal.utf8")

local function write_row(state, row, codepoints)
  state:set_cursor(0, row)
  for _, codepoint in ipairs(codepoints) do
    state:write_codepoint(Utf8.encode(codepoint), codepoint)
  end
end

return {
  search_maps_unicode_matches_to_whole_grapheme_cells = function()
    local state = State.new(5, 2)
    write_row(state, 0, { 0x61, 0x4e2d, 0x62 })
    write_row(state, 1, { 0x4e2d, 0x61 })
    state:search_begin("forward")
    Assert.truthy(state:search_append("中"))
    local match, status = state:search_submit("forward")
    Assert.equal(status, "matches")
    Assert.equal(match.start_column, 1)
    Assert.equal(match.finish_column, 3)
    match, status = state:search_navigate("forward")
    Assert.equal(status, "matches")
    Assert.equal(match.start_column, 0)
    Assert.equal(match.finish_column, 2)
    match = state:search_navigate("backward")
    Assert.equal(match.start_column, 1)
  end,

  search_reveals_retained_history_without_changing_selection = function()
    local state = State.new(3, 2)
    write_row(state, 0, { 0x6f, 0x6c, 0x64 })
    state:set_selection(1, 0, 1, 1)
    local selection = state:selection_view()
    state:scroll_up(1)
    write_row(state, 1, { 0x6e, 0x65, 0x77 })
    state:search_begin("forward")
    Assert.truthy(state:search_append("old"))
    local match = state:search_submit("forward")
    Assert.equal(match.start_column, 0)
    Assert.equal(state.history_offset, 1)
    local after = state:selection_view()
    Assert.equal(after.anchor.line_id, selection.anchor.line_id)
    Assert.equal(after.focus.line_id, selection.focus.line_id)
  end,

  search_reports_empty_no_match_and_stale_documents = function()
    local state = State.new(4, 1)
    write_row(state, 0, { 0x61, 0x61, 0x61, 0x61 })
    state:search_begin("forward")
    local match, status = state:search_submit("forward")
    Assert.equal(match, nil)
    Assert.equal(status, "empty")
    state:search_begin("forward")
    Assert.truthy(state:search_append("zz"))
    match, status = state:search_submit("forward")
    Assert.equal(match, nil)
    Assert.equal(status, "no-match")
    state:search_begin("forward")
    Assert.truthy(state:search_append("aa"))
    match, status = state:search_submit("forward")
    Assert.equal(status, "matches")
    Assert.equal(state:search_view().match_count, 3)
    match, status = state:search_navigate("forward")
    Assert.equal(status, "matches")
    Assert.equal(match.start_column, 1)
    state:set_cursor(0, 0)
    state:write_codepoint("b", 0x62)
    match, status = state:search_navigate("forward")
    Assert.equal(match, nil)
    Assert.equal(status, "stale")
    Assert.equal(state:search_view().status, "stale")
  end,
}
