local Assert = require("tests.assert")
local Workspace = require("kiwi.session.workspace")

return {
  workspace_models_tabs_and_split_layout_without_host_objects = function()
    local workspace = Workspace.new()
    local first, tab = workspace:new_tab({ name = "first" })
    Assert.equal(tab.id, 1)
    local second = assert(workspace:split("vertical", { name = "second" }, { ratio = 0.4 }))
    local third = assert(workspace:split("horizontal", { name = "third" }, { ratio = 0.5 }))
    Assert.equal(workspace:active_pane().id, third.id)
    local layout = workspace:layout(100, 40)
    Assert.equal(#layout, 3)
    Assert.equal(layout[1].pane_id, first.id)
    Assert.equal(layout[1].width, 40)
    Assert.equal(layout[2].pane_id, second.id)
    Assert.equal(layout[2].width, 60)
    Assert.equal(layout[2].height, 20)
    Assert.equal(layout[3].pane_id, third.id)
    Assert.equal(layout[3].x, 40)
    Assert.equal(layout[3].y, 20)
  end,
  workspace_closes_panes_and_tabs_with_explicit_host_lifecycle = function()
    local closed = {}
    local workspace = Workspace.new({ on_close = function(session, metadata) closed[#closed + 1] = { session = session, metadata = metadata } end })
    local first, first_tab = workspace:new_tab("one")
    local second = assert(workspace:split("horizontal", "two"))
    Assert.truthy(workspace:close_pane(second.id))
    Assert.equal(workspace:active_pane().id, first.id)
    Assert.equal(closed[1].session, "two")
    Assert.truthy(not workspace:close_pane(first.id))
    local third, second_tab = workspace:new_tab("three")
    Assert.truthy(workspace:focus_tab(first_tab.id))
    Assert.truthy(workspace:close_tab(first_tab.id))
    Assert.equal(closed[2].session, "one")
    Assert.equal(workspace:active_tab().id, second_tab.id)
    Assert.equal(workspace:active_pane().id, third.id)
  end,
  workspace_enforces_bounded_tab_and_pane_counts = function()
    local workspace = Workspace.new({ maximum_panes = 2, maximum_tabs = 1 })
    assert(workspace:new_tab({}))
    assert(workspace:split("vertical", {}))
    local _, reason = workspace:split("vertical", {})
    Assert.equal(reason, "pane-limit")
    local _, tab_reason = workspace:new_tab({})
    Assert.equal(tab_reason, "tab-limit")
  end,
  workspace_mutates_inactive_tabs_and_rejects_layouts_smaller_than_their_panes = function()
    local workspace = Workspace.new()
    local first, first_tab = workspace:new_tab("one")
    local second = assert(workspace:split("vertical", "two"))
    local _, second_tab = workspace:new_tab("three")
    Assert.truthy(workspace:set_split_ratio(second.id, 0.7))
    Assert.truthy(workspace:focus_tab(first_tab.id))
    local layout, reason = workspace:layout(1, 20)
    Assert.equal(layout, nil)
    Assert.equal(reason, "insufficient-space")
    layout = assert(workspace:layout(2, 20))
    Assert.equal(layout[1].width, 1)
    Assert.equal(layout[2].width, 1)
    Assert.truthy(workspace:focus_tab(second_tab.id))
    Assert.equal(workspace:active_pane().session, "three")
    Assert.equal(first.session, "one")
  end,
  workspace_snapshot_excludes_host_session_data = function()
    local workspace = Workspace.new()
    local pane = assert(workspace:new_tab({ secret = "not serialized" }))
    local snapshot = workspace:snapshot()
    Assert.equal(snapshot.tabs[1].root.pane_id, pane.id)
    Assert.equal(snapshot.tabs[1].root.session, nil)
  end,
  workspace_restores_topology_with_fresh_host_sessions = function()
    local workspace = Workspace.new()
    local first, first_tab = workspace:new_tab({ id = "old-first" })
    local second = assert(workspace:split("vertical", { id = "old-second" }, { ratio = 0.4 }))
    local third, second_tab = workspace:new_tab({ id = "old-third" })
    assert(workspace:focus_tab(first_tab.id))
    assert(workspace:focus_pane(second.id))
    local snapshot = workspace:snapshot()
    local restored = Workspace.restore(snapshot, function(pane_id, tab_id)
      return { id = "fresh-" .. pane_id .. "-" .. tab_id }
    end)
    Assert.equal(restored:active_tab().id, first_tab.id)
    Assert.equal(restored:active_pane().id, second.id)
    Assert.equal(restored:active_pane().session.id, "fresh-" .. second.id .. "-" .. first_tab.id)
    Assert.equal(restored:layout(100, 30)[1].width, 40)
    Assert.equal(restored:tab(second_tab.id).active_pane_id, third.id)
    Assert.equal(restored.panes[first.id].session.id, "fresh-" .. first.id .. "-" .. first_tab.id)
  end,
  workspace_hit_testing_reuses_the_active_tab_cell_layout = function()
    local workspace = Workspace.new()
    local first = assert(workspace:new_tab("one"))
    local second = assert(workspace:split("vertical", "two", { ratio = 0.4 }))
    local left, left_layout = assert(workspace:pane_at(100, 30, 39, 29))
    Assert.equal(left.id, first.id)
    Assert.equal(left_layout.width, 40)
    local right, right_layout = assert(workspace:pane_at(100, 30, 40, 0))
    Assert.equal(right.id, second.id)
    Assert.equal(right_layout.x, 40)
    local outside, reason = workspace:pane_at(100, 30, 100, 0)
    Assert.equal(outside, nil)
    Assert.equal(reason, "outside-workspace")
  end,
}
