local Assert = require("tests.assert")
local Actions = require("kiwi.terminal.actions")
local Base64 = require("kiwi.terminal.base64")
local bit = require("bit")
local Color = require("kiwi.renderer.color")
local Parser = require("kiwi.terminal.parser")
local Snapshot = require("kiwi.terminal.snapshot")
local State = require("kiwi.terminal.state")

local function text_at(state, row)
  local characters = {}
  for column = 0, state.columns - 1 do
    characters[#characters + 1] = state:get(column, row).glyph
  end
  return table.concat(characters)
end

return {
  terminal_state_uses_deferred_autowrap = function()
    local state = State.new(3, 2)
    state.damage:clear()
    state:write_codepoint("A")
    state:write_codepoint("B")
    state:write_codepoint("C")
    Assert.equal(text_at(state, 0), "ABC")
    Assert.equal(state.cursor.column, 2)
    Assert.truthy(state.cursor.pending_wrap)
    state:write_codepoint("D")
    Assert.equal(text_at(state, 1), "D  ")
    Assert.equal(state.cursor.column, 1)
    Assert.equal(state.cursor.row, 1)
  end,
  terminal_state_scrolls_margins_without_rebuilding_other_rows = function()
    local state = State.new(4, 4)
    for row = 0, 3 do
      state:set_cell(0, row, state:cell_from_attributes(tostring(row)))
    end
    Assert.truthy(state:set_margins(2, 4))
    state:scroll_up(1)
    Assert.equal(state:get(0, 0).glyph, "0")
    Assert.equal(state:get(0, 1).glyph, "2")
    Assert.equal(state:get(0, 2).glyph, "3")
    Assert.equal(state:get(0, 3).glyph, " ")
  end,
  terminal_state_applies_left_right_margins_to_editing_and_origin_addressing = function()
    local state = State.new(8, 3)
    Parser.new(state):feed("ABC123\27[?69h\27[3;5s\27[4G\27[P")
    Assert.equal(text_at(state, 0), "ABC2 3  ")
    Assert.equal(state.active_screen.left_margin, 2)
    Assert.equal(state.active_screen.right_margin, 4)

    Parser.new(state):feed("\27[2;3r\27[?6h\27[1;1HX")
    Assert.equal(state:get(2, 1).glyph, "X")
    Assert.equal(state.cursor.column, 3)
    Assert.equal(state.cursor.row, 1)
    Parser.new(state):feed("\27[6n\27[?6n")
    local responses = state:pop_responses()
    Assert.equal(responses[1], "\27[1;2R")
    Assert.equal(responses[2], "\27[?1;2R")

    Parser.new(state):feed("\27[?69l")
    Assert.equal(state.modes.left_right_margin, false)
    Assert.equal(state.active_screen.left_margin, 0)
    Assert.equal(state.active_screen.right_margin, 7)
  end,
  terminal_state_translates_dec_graphics_and_restores_saved_character_sets = function()
    local state = State.new(12, 1)
    Parser.new(state):feed("\27(0lqk\27)0\14x\15x\27(Bx\27(A#")
    Assert.equal(text_at(state, 0), "┌─┐││x£     ")
    Assert.equal(state.character_sets.g0, "uk")
    Assert.equal(state.character_sets.g1, "dec_special_graphics")
    Assert.equal(state.character_sets.gl, "g0")

    Parser.new(state):feed("\27(0" .. string.char(27) .. "7\27(Bx")
    Assert.equal(state:get(7, 0).glyph, "x")
    state:resize(13, 1)
    Parser.new(state):feed(string.char(27) .. "8x")
    Assert.equal(state:get(7, 0).glyph, "│")
    Parser.new(state):feed("\27cx")
    Assert.equal(state:get(0, 0).glyph, "x")
    Assert.equal(state.character_sets.g0, "ascii")
    Assert.equal(state.character_sets.g1, "ascii")
  end,
  terminal_state_keeps_alternate_screen_out_of_primary_scrollback = function()
    local state = State.new(3, 2, { scrollback_limit = 4 })
    state:set_cell(0, 0, state:cell_from_attributes("P"))
    state:scroll_up(1)
    Assert.equal(state.scrollback:size(), 1)
    state:switch_alternate(true, true)
    state:set_cell(0, 1, state:cell_from_attributes("A"))
    state:scroll_up(1)
    Assert.equal(state.scrollback:size(), 1)
    state:switch_alternate(false, true)
    Assert.equal(state.active_screen, state.primary)
    Assert.equal(state.scrollback:size(), 1)
  end,
  terminal_state_resolves_sgr_colours_and_inverse = function()
    local state = State.new(4, 1)
    state:apply(Actions.csi({ 38, 2, 1, 2, 3, 48, 5, 12, 7 }, "", "", "m"))
    state:write_codepoint("X")
    local cell = state:get(0, 0)
    Assert.equal(cell.glyph, "X")
    Assert.truthy(cell.fg ~= cell.bg)
    Assert.truthy(cell.flags ~= 0)
    state:apply(Actions.csi({ 0 }, "", "", "m"))
    state:write_codepoint("Y")
    Assert.equal(state:get(1, 0).flags, 0)
  end,
  terminal_state_applies_reverse_screen_video_at_the_presentation_boundary = function()
    local state = State.new(3, 1)
    state:write_codepoint("A")
    local cell = state:get(0, 0)
    local original_foreground, original_background = cell.fg, cell.bg
    state.damage:clear()
    state.text_damage:clear()
    Parser.new(state):feed("\27[?5h\27[?5$p")
    Assert.equal(state.modes.reverse_video, true)
    Assert.equal(state:pop_responses()[1], "\27[?5;1$y")
    Assert.equal(cell.fg, original_foreground)
    Assert.equal(cell.bg, original_background)
    local foreground, background = state:presentation_colors(cell)
    Assert.equal(foreground, original_background)
    Assert.equal(background, original_foreground)
    Assert.equal(Snapshot.value(state).modes.reverse_video, true)
    Assert.truthy(state.damage.full)
    Assert.truthy(state.text_damage.full)
    Parser.new(state):feed("\27[?5l\27[?5$p\27[?5h\27[!p")
    Assert.equal(state:pop_responses()[1], "\27[?5;2$y")
    Assert.equal(state.modes.reverse_video, false)
    foreground, background = state:presentation_colors(cell)
    Assert.equal(foreground, original_foreground)
    Assert.equal(background, original_background)
    Assert.equal(Snapshot.value(state).modes.reverse_video, false)
  end,
  terminal_state_accepts_colon_form_sgr_underline_without_claiming_style_variants = function()
    local state = State.new(4, 1)
    state:apply(Actions.csi({ 4, 3 }, "", "", "m", true))
    state:write_codepoint("U")
    Assert.equal(state:get(0, 0).flags, State.flags.underline)
    state:apply(Actions.csi({ 4, 0 }, "", "", "m", true))
    state:write_codepoint("N")
    Assert.equal(state:get(1, 0).flags, 0)
    Assert.equal(state.stats.unknown.csi, 0)
  end,
  terminal_state_accepts_colon_form_sgr_indexed_and_direct_colours = function()
    local state = State.new(4, 1)
    local parser = Parser.new(state)
    parser:feed("\27[38:2:17:34:51;48:2::68:85:102mR\27[38:5:196mI")
    local direct_foreground = Color.unpack(state:get(0, 0).fg)
    local direct_background = Color.unpack(state:get(0, 0).bg)
    Assert.equal(direct_foreground.red, 17)
    Assert.equal(direct_foreground.green, 34)
    Assert.equal(direct_foreground.blue, 51)
    Assert.equal(direct_background.red, 68)
    Assert.equal(direct_background.green, 85)
    Assert.equal(direct_background.blue, 102)
    local indexed = Color.unpack(state:get(1, 0).fg)
    Assert.equal(indexed.red, 255)
    Assert.equal(indexed.green, 0)
    Assert.equal(indexed.blue, 0)
    Assert.equal(state.stats.unknown.csi, 0)
  end,
  terminal_state_answers_xtgettcap_for_its_documented_runtime_subset = function()
    local state = State.new(4, 1)
    local parser = Parser.new(state)
    parser:feed("\27P+q436f;544e;524742\27\\")
    Assert.equal(state:pop_responses()[1], "\27P1+r436f=323536;544e=787465726d2d6b697769;524742=38\27\\")
    parser:feed("\27P+q5463;73657472676266;73657472676262\27\\")
    Assert.equal(state:pop_responses()[1], "\27P0+r\27\\")
    Assert.equal(parser.stats.ignored, 0)
    Assert.equal(state.stats.unknown.dcs or 0, 0)
  end,
  terminal_state_applies_and_resets_osc_palette_colours_to_existing_cells = function()
    local state = State.new(4, 1)
    state:apply(Actions.csi({ 31 }, "", "", "m"))
    state:write_codepoint("R")
    local red = state:get(0, 0)
    Assert.equal(red.fg_slot, 2)
    state:apply(Actions.osc(4, "1;#010203"))
    local changed = Color.unpack(state:get(0, 0).fg)
    Assert.equal(changed.red, 1)
    Assert.equal(changed.green, 2)
    Assert.equal(changed.blue, 3)
    state:apply(Actions.osc(4, "1;?"))
    Assert.equal(state:pop_responses()[1], "\27]4;1;rgb:0101/0202/0303\27\\")
    state:apply(Actions.osc(104, "1"))
    Assert.truthy(state:get(0, 0).fg ~= Color.pack(1, 2, 3, 0xff))
  end,
  terminal_state_applies_osc_default_colours_without_mutating_literal_rgb_cells = function()
    local state = State.new(3, 1)
    state:write_codepoint("D")
    state:apply(Actions.csi({ 38, 2, 9, 8, 7 }, "", "", "m"))
    state:write_codepoint("L")
    state:apply(Actions.osc(10, "rgb:1212/3434/5656"))
    local default = Color.unpack(state:get(0, 0).fg)
    local literal = Color.unpack(state:get(1, 0).fg)
    Assert.equal(default.red, 0x12)
    Assert.equal(default.green, 0x34)
    Assert.equal(default.blue, 0x56)
    Assert.equal(literal.red, 9)
    Assert.equal(literal.green, 8)
    Assert.equal(literal.blue, 7)
    state:apply(Actions.osc(11, "?"))
    Assert.truthy(state:pop_responses()[1]:match("^\27%]11;rgb:"))
  end,
  terminal_state_applies_queries_and_resets_osc_cursor_colour = function()
    local effects = {}
    local state = State.new(3, 1, { effect_sink = function(kind, value) effects[#effects + 1] = { kind = kind, value = value } end })
    local initial = state.cursor_color
    state:apply(Actions.osc(12, "#010203"))
    Assert.equal(state.cursor_color, Color.pack(1, 2, 3, 0xff))
    Assert.equal(effects[#effects].kind, "cursor_color_changed")
    state:apply(Actions.osc(12, "?"))
    Assert.equal(state:pop_responses()[1], "\27]12;rgb:0101/0202/0303\27\\")
    state:apply(Actions.osc(112, ""))
    Assert.equal(state.cursor_color, initial)
    Assert.truthy(effects[#effects].value.reset)
  end,
  terminal_state_denies_osc52_unless_the_host_explicitly_enables_it = function()
    local effects = {}
    local state = State.new(4, 1, { effect_sink = function(kind, value) effects[#effects + 1] = { kind = kind, value = value } end })
    state:apply(Actions.osc(52, "c;" .. Base64.encode("clipboard text")))
    Assert.equal(effects[#effects].kind, "clipboard_write_denied")
    Assert.equal(effects[#effects].value.reason, "disabled")
    state:configure_osc52_write(true)
    state:apply(Actions.osc(52, "c;" .. Base64.encode("clipboard text")))
    Assert.equal(effects[#effects].kind, "clipboard_write_requested")
    Assert.equal(effects[#effects].value.text, "clipboard text")
    state:apply(Actions.osc(52, "c;%%%%"))
    Assert.equal(effects[#effects].kind, "clipboard_write_denied")
    Assert.equal(effects[#effects].value.reason, "invalid")
  end,
  terminal_state_emits_bounded_notification_and_progress_effects = function()
    local effects = {}
    local state = State.new(4, 1, { effect_sink = function(kind, value) effects[#effects + 1] = { kind = kind, value = value } end })
    state:apply(Actions.osc(9, "build completed"))
    Assert.equal(effects[#effects].kind, "notification_requested")
    Assert.equal(effects[#effects].value.body, "build completed")
    state:apply(Actions.osc(9, "4;1;73"))
    Assert.equal(effects[#effects].kind, "progress_changed")
    Assert.equal(effects[#effects].value.progress, 73)
    Assert.equal(effects[#effects].value.state, 1)
    state:apply(Actions.osc(9, "4;3"))
    Assert.equal(effects[#effects].kind, "progress_changed")
    Assert.equal(effects[#effects].value.progress, nil)
    Assert.equal(effects[#effects].value.state, 3)
    state:apply(Actions.osc(9, "4;1"))
    Assert.equal(state.stats.unknown.osc, 1)
    state:apply(Actions.osc(9, "4;1;101"))
    Assert.equal(state.stats.unknown.osc, 2)
  end,
  terminal_state_configures_a_complete_host_theme_without_losing_palette_sources = function()
    local state = State.new(3, 1)
    state:apply(Actions.csi({ 31 }, "", "", "m"))
    state:write_codepoint("R")
    state:configure_palette({
      foreground = Color.pack(1, 2, 3, 0xff),
      background = Color.pack(4, 5, 6, 0xff),
      palette = { [1] = Color.pack(7, 8, 9, 0xff) },
    })
    Assert.equal(state:get(0, 0).fg_slot, 2)
    Assert.equal(Color.unpack(state:get(0, 0).fg).blue, 9)
    state:apply(Actions.csi({ 0 }, "", "", "m"))
    state:write_codepoint("D")
    Assert.equal(Color.unpack(state:get(1, 0).fg).red, 1)
    Assert.equal(Color.unpack(state:get(1, 0).bg).green, 5)
  end,
  terminal_state_emits_conservative_status_responses = function()
    local state = State.new(4, 2)
    state:set_cursor(2, 1)
    state:apply(Actions.csi({ 5 }, "", "", "n"))
    state:apply(Actions.csi({ 6 }, "", "", "n"))
    state:apply(Actions.csi({}, "", "", "c"))
    local responses = state:pop_responses()
    Assert.equal(responses[1], "\27[0n")
    Assert.equal(responses[2], "\27[2;3R")
    Assert.equal(responses[3], "\27[?1;0c")
  end,
  terminal_state_reports_only_conservative_primary_and_secondary_device_attributes = function()
    local state = State.new(4, 2)
    Parser.new(state):feed("\27[c\27[0c\27[>c\27[>0c\27[>1c")
    local responses = state:pop_responses()
    Assert.equal(responses[1], "\27[?1;0c")
    Assert.equal(responses[2], "\27[?1;0c")
    Assert.equal(responses[3], "\27[>0;1;0c")
    Assert.equal(responses[4], "\27[>0;1;0c")
    Assert.equal(state.stats.unknown.csi, 1)
  end,
  terminal_state_reports_declared_text_geometry_without_accepting_window_mutation = function()
    local state = State.new(4, 2, { cell_width = 9, cell_height = 17 })
    Parser.new(state):feed("\27[14t\27[16t\27[18t")
    local responses = state:pop_responses()
    Assert.equal(responses[1], "\27[4;34;36t")
    Assert.equal(responses[2], "\27[6;17;9t")
    Assert.equal(responses[3], "\27[8;2;4t")

    state:resize(5, 3)
    state:apply(Actions.csi({ 18 }, "", "", "t"))
    Assert.equal(state:pop_responses()[1], "\27[8;3;5t")
    state:apply(Actions.csi({ 8, 24, 80 }, "", "", "t"))
    Assert.equal(state.stats.unknown.csi, 1)
  end,
  terminal_state_requires_host_cell_metrics_for_pixel_geometry_queries = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 14 }, "", "", "t"))
    Assert.equal(#state:pop_responses(), 0)
    Assert.equal(state.stats.unknown.csi, 1)
  end,
  terminal_state_reports_the_declared_standard_and_dec_mode_subset = function()
    local state = State.new(4, 2)
    Parser.new(state):feed("\27[4$p\27[20$p\27[?7$p\27[?67$p\27[?69$p")
    local responses = state:pop_responses()
    Assert.equal(responses[1], "\27[4;2$y")
    Assert.equal(responses[2], "\27[20;2$y")
    Assert.equal(responses[3], "\27[?7;1$y")
    Assert.equal(responses[4], "\27[?67;2$y")
    Assert.equal(responses[5], "\27[?69;2$y")

    state:apply(Actions.csi({ 4 }, "", "", "h"))
    state:apply(Actions.csi({ 20 }, "", "", "h"))
    state:apply(Actions.csi({ 67 }, "?", "", "h"))
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    state:apply(Actions.csi({ 4 }, "", "$", "p"))
    state:apply(Actions.csi({ 20 }, "", "$", "p"))
    state:apply(Actions.csi({ 67 }, "?", "$", "p"))
    state:apply(Actions.csi({ 1049 }, "?", "$", "p"))
    responses = state:pop_responses()
    Assert.equal(responses[1], "\27[4;1$y")
    Assert.equal(responses[2], "\27[20;1$y")
    Assert.equal(responses[3], "\27[?67;1$y")
    Assert.equal(responses[4], "\27[?1049;1$y")

    state:apply(Actions.csi({ 1, 2 }, "?", "$", "p"))
    Assert.equal(state.stats.unknown.csi, 1)
  end,
  terminal_state_negotiates_backarrow_input_mode_through_reset = function()
    local state = State.new(4, 1)
    state:apply(Actions.csi({ 67 }, "?", "", "h"))
    Assert.equal(state:input_modes().backarrow, true)
    state:soft_reset()
    Assert.equal(state:input_modes().backarrow, false)
    state:apply(Actions.csi({ 67 }, "?", "", "h"))
    state:apply(Actions.esc("c"))
    Assert.equal(state:input_modes().backarrow, false)
  end,
  terminal_state_models_xterm_reverse_wrap_with_margins_and_pending_wrap = function()
    local state = State.new(4, 3)
    state:apply(Actions.csi({ 45 }, "?", "", "h"))
    state:set_cursor(0, 1)
    state:backspace()
    Assert.equal(state.cursor.column, 3)
    Assert.equal(state.cursor.row, 0)

    state:set_cursor(0, 0)
    state:backspace()
    Assert.equal(state.cursor.column, 3)
    Assert.equal(state.cursor.row, 2)

    state:apply(Actions.csi({ 2, 3 }, "", "", "r"))
    state:set_cursor(0, 1)
    state:backspace()
    Assert.equal(state.cursor.column, 3)
    Assert.equal(state.cursor.row, 2)

    Assert.truthy(state:set_margins(1, 3))
    state:apply(Actions.csi({ 69 }, "?", "", "h"))
    Assert.truthy(state:set_left_right_margins(2, 3))
    state:set_cursor(1, 1)
    state:backspace()
    Assert.equal(state.cursor.column, 2)
    Assert.equal(state.cursor.row, 0)

    state:set_cursor(2, 1)
    state.cursor.pending_wrap = true
    state:backspace()
    Assert.equal(state.cursor.column, 2)
    Assert.equal(state.cursor.row, 1)
    Assert.equal(state.cursor.pending_wrap, false)

    state:apply(Actions.csi({ 7 }, "?", "", "l"))
    state:set_cursor(1, 1)
    state:backspace()
    Assert.equal(state.cursor.column, 1)
    Assert.equal(state.cursor.row, 1)

    state:apply(Actions.csi({ 45 }, "?", "$", "p"))
    Assert.equal(state:pop_responses()[1], "\27[?45;1$y")
    state:soft_reset()
    Assert.equal(state.modes.reverse_wrap, false)
  end,
  terminal_state_restores_the_declared_independent_private_mode_subset = function()
    local state = State.new(4, 2)
    Parser.new(state):feed("\27[?1;45;67;1004;2004h\27[?1;45;67;1004;2004s")
    Assert.equal(state.modes.application_cursor, true)
    Assert.equal(state.modes.reverse_wrap, true)
    Assert.equal(state.modes.backarrow, true)
    Assert.equal(state.modes.focus_reporting, true)
    Assert.equal(state.modes.bracketed_paste, true)

    Parser.new(state):feed("\27[?1;45;67;1004;2004l\27[?1;45;67;1004;2004r")
    Assert.equal(state.modes.application_cursor, true)
    Assert.equal(state.modes.reverse_wrap, true)
    Assert.equal(state.modes.backarrow, true)
    Assert.equal(state.modes.focus_reporting, true)
    Assert.equal(state.modes.bracketed_paste, true)

    state:apply(Actions.esc("c"))
    state:apply(Actions.csi({ 1 }, "?", "", "r"))
    Assert.equal(state.modes.application_cursor, false)
    Parser.new(state):feed("\27[?1002;1016h\27[?1002;1016s\27[?1002;1016l\27[?1002;1016r")
    Assert.equal(state.modes.mouse_tracking, "button")
    Assert.equal(state.modes.mouse_protocol, "sgr-pixels")
    state:apply(Actions.csi({ 1002 }, "?", "$", "p"))
    Assert.equal(state:pop_responses()[1], "\27[?1002;1$y")

    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    state:apply(Actions.csi({ 1049 }, "?", "", "s"))
    state:apply(Actions.csi({ 1049 }, "?", "", "l"))
    Assert.equal(state.active_screen, state.primary)
    state:apply(Actions.csi({ 1049 }, "?", "", "r"))
    Assert.equal(state.active_screen, state.alternate)
  end,
  terminal_state_models_xterm_tab_clear_and_default_tab_reset = function()
    local state = State.new(20, 1)
    state:apply(Actions.csi({ 3 }, "", "", "g"))
    state:apply(Actions.csi({ 2 }, "", "", "g"))
    state:apply(Actions.execute(0x09))
    Assert.equal(state.cursor.column, 19)

    state:set_cursor(0, 0)
    state:apply(Actions.csi({ 5 }, "?", "", "W"))
    state:apply(Actions.execute(0x09))
    Assert.equal(state.cursor.column, 8)

    state:apply(Actions.csi({}, "", "", "g"))
    state:set_cursor(0, 0)
    state:apply(Actions.execute(0x09))
    Assert.equal(state.cursor.column, 16)
  end,
  terminal_state_models_automatic_newline_mode_and_resets_it = function()
    local state = State.new(4, 2)
    Parser.new(state):feed("A\nB")
    Assert.equal(text_at(state, 0), "A   ")
    Assert.equal(text_at(state, 1), " B  ")

    state:reset()
    Parser.new(state):feed("A\27[20h\nB")
    Assert.equal(text_at(state, 0), "A   ")
    Assert.equal(text_at(state, 1), "B   ")
    Assert.equal(state.modes.newline, true)

    state:soft_reset()
    Assert.equal(state.modes.newline, false)
    state:apply(Actions.csi({ 20 }, "", "", "h"))
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.newline, false)
  end,
  terminal_state_selectively_erases_only_unprotected_cells = function()
    local state = State.new(5, 1)
    Parser.new(state):feed("\27[1\"qAB\27[0\"qCD\27[1;1H\27[?0J")
    Assert.equal(text_at(state, 0), "AB   ")
    Assert.truthy(bit.band(state:get(0, 0).flags, State.flags.protected) ~= 0)
    Assert.truthy(bit.band(state:get(1, 0).flags, State.flags.protected) ~= 0)

    Parser.new(state):feed("\27[1;1H\27[0J")
    Assert.equal(text_at(state, 0), "     ")

    Parser.new(state):feed("\27[1\"qA\27[0\"qBCD\27[1;3H\27[?1K")
    Assert.equal(text_at(state, 0), "A  D ")

    state:apply(Actions.csi({ 3 }, "?", "", "J"))
    Assert.equal(state.stats.unknown.csi, 1)

    state:apply(Actions.csi({ 1 }, "", "\"", "q"))
    state:soft_reset()
    Assert.equal(state.active_screen.attributes.protected, false)
  end,
  terminal_state_models_cursor_style_across_alternate_and_reset = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 3 }, "", " ", "q"))
    Assert.equal(state.modes.cursor_style, 3)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.cursor_style, 3)
    state:apply(Actions.csi({ 6 }, "", " ", "q"))
    state:apply(Actions.csi({ 1049 }, "?", "", "l"))
    Assert.equal(state.modes.cursor_style, 6)
    state:apply(Actions.csi({ 0 }, "", " ", "q"))
    Assert.equal(state.modes.cursor_style, 1)
    state:apply(Actions.csi({ 7 }, "", " ", "q"))
    Assert.equal(state.stats.unknown.csi, 1)
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.cursor_style, 1)
  end,
  terminal_state_honours_dec_cursor_blink_mode_without_changing_cursor_shape = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 3 }, "", " ", "q"))
    state:apply(Actions.csi({ 12 }, "?", "", "l"))
    Assert.equal(state.modes.cursor_style, 3)
    Assert.equal(state.modes.cursor_blink, false)
    state:apply(Actions.csi({ 12 }, "?", "", "h"))
    Assert.equal(state.modes.cursor_blink, true)
    state:apply(Actions.csi({ 12 }, "?", "$", "p"))
    Assert.equal(state:pop_responses()[1], "\27[?12;1$y")
    state:soft_reset()
    Assert.equal(state.modes.cursor_blink, true)
  end,
  terminal_state_tracks_xterm_modify_other_keys_levels = function()
    local state = State.new(4, 2)
    Parser.new(state):feed("\27[>4;2m\27[>4;0m")
    Assert.equal(state.modes.modify_other_keys, 0)
    state:apply(Actions.csi({ 4, 3 }, ">", "", "m"))
    Assert.equal(state.modes.modify_other_keys, 3)
    state:apply(Actions.csi({ 4, 4 }, ">", "", "m"))
    Assert.equal(state.stats.unknown.csi, 1)
    state:soft_reset()
    Assert.equal(state.modes.modify_other_keys, 0)
  end,
  terminal_state_restores_bounded_xterm_window_and_icon_title_stacks = function()
    local effects = {}
    local state = State.new(4, 2, { effect_sink = function(kind, value) effects[#effects + 1] = { kind = kind, value = value } end })
    Parser.new(state):feed("\27]0;original\7\27[22;2t\27]2;replacement\7\27[22;1t\27]1;icon\7\27[23;2t\27[23;1t")
    Assert.equal(state.title, "original")
    Assert.equal(state.icon_title, "original")
    Assert.equal(#state.title_stacks.window, 0)
    Assert.equal(#state.title_stacks.icon, 0)
    Assert.equal(effects[#effects].kind, "title_changed")
    Assert.equal(effects[#effects].value.title, "original")
    Assert.equal(state.stats.unknown.csi, 0)
  end,
  terminal_state_resets_synchronized_output_and_rejects_unknown_modes = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 2026 }, "?", "", "h"))
    state:apply(Actions.csi({ 2026 }, "?", "", "h"))
    Assert.equal(state.modes.synchronized_output, true)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.synchronized_output, true)
    state:apply(Actions.csi({ 2026 }, "?", "", "l"))
    Assert.equal(state.modes.synchronized_output, false)
    state:apply(Actions.csi({ 2027 }, "?", "", "h"))
    Assert.equal(state.stats.unknown.csi, 1)
    state:apply(Actions.csi({ 2026 }, "?", "", "h"))
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.synchronized_output, false)
  end,
  terminal_state_tracks_mutually_exclusive_mouse_protocols_and_encodings_through_reset = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 1002, 1006, 1004 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "button")
    Assert.equal(state.modes.mouse_sgr, true)
    Assert.equal(state.modes.focus_reporting, true)
    local generation = state.modes.mouse_generation
    state:apply(Actions.csi({ 1003 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "any")
    Assert.truthy(state.modes.mouse_generation > generation)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "any")
    state:apply(Actions.csi({ 1049 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_sgr, true)
    state:apply(Actions.csi({ 1002 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "any")
    state:apply(Actions.csi({ 1003, 1006 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "none")
    Assert.equal(state.modes.mouse_sgr, false)
    state:apply(Actions.csi({ 1000, 1002 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "button")
    state:apply(Actions.csi({ 1002 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "none")
    state:apply(Actions.csi({ 1000 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "none")
    state:apply(Actions.csi({ 9, 1005 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "x10")
    Assert.equal(state.modes.mouse_protocol, "utf8")
    state:apply(Actions.csi({ 1015 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_protocol, "urxvt")
    state:apply(Actions.csi({ 1006 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_protocol, "sgr")
    state:apply(Actions.csi({ 1006 }, "?", "$", "p"))
    Assert.equal(state:pop_responses()[1], "\27[?1006;1$y")
    state:apply(Actions.csi({ 1016 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_protocol, "sgr-pixels")
    Assert.equal(state.modes.mouse_pixels, true)
    Assert.equal(state.modes.mouse_sgr, false)
    state:apply(Actions.csi({ 1016 }, "?", "$", "p"))
    Assert.equal(state:pop_responses()[1], "\27[?1016;1$y")
    state:apply(Actions.csi({ 1016 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_protocol, "x10")
    state:apply(Actions.csi({ 1007 }, "?", "", "h"))
    Assert.equal(state.modes.alternate_scroll, true)
    state:apply(Actions.csi({ 1007 }, "?", "$", "p"))
    Assert.equal(state:pop_responses()[1], "\27[?1007;1$y")
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.alternate_scroll, false)
    Assert.equal(state.modes.focus_reporting, false)
    Assert.equal(state.modes.mouse_protocol, "x10")
  end,
  terminal_state_negotiates_bounded_kitty_keyboard_disambiguation = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({}, "?", "", "u"))
    Assert.equal(state:pop_responses()[1], "\27[?0u")
    state:apply(Actions.csi({ 1 }, ">", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 1)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.keyboard_flags, 0)
    state:apply(Actions.csi({ 1 }, ">", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 1)
    state:apply(Actions.csi({}, "<", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 0)
    state:apply(Actions.csi({ 1049 }, "?", "", "l"))
    Assert.equal(state.modes.keyboard_flags, 1)
    state:apply(Actions.csi({}, "<", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 0)
    state:apply(Actions.csi({ 1, 4 }, "=", "", "u"))
    Assert.equal(state.stats.unknown.csi, 1)
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.keyboard_flags, 0)
    for index = 1, 9 do
      state:apply(Actions.csi({ index % 2 }, ">", "", "u"))
    end
    Assert.equal(#state.active_screen.keyboard_stack, 8)
  end,
  terminal_state_negotiates_all_kitty_keyboard_progressive_enhancement_flags = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 31 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 27)
    state:apply(Actions.csi({ 6 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 2)
    state:apply(Actions.csi({ 9, 2 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 11)
    state:apply(Actions.csi({ 8, 3 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 3)
    state:apply(Actions.csi({}, "?", "", "u"))
    Assert.equal(state:pop_responses()[1], "\27[?3u")
    state:apply(Actions.csi({ 16 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 0)
    state:apply(Actions.csi({ 24 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 24)

    local alternate_keys = State.new(4, 2, { keyboard_supported_flags = 31 })
    alternate_keys:apply(Actions.csi({ 31 }, "=", "", "u"))
    Assert.equal(alternate_keys.modes.keyboard_flags, 31)
    alternate_keys:apply(Actions.csi({}, "?", "", "u"))
    Assert.equal(alternate_keys:pop_responses()[1], "\27[?31u")
  end,
  terminal_state_handles_xterm_alignment_keypad_soft_reset_tabs_and_repeat = function()
    local state = State.new(12, 2)
    state:apply(Actions.esc("=", ""))
    Assert.equal(state.modes.application_keypad, true)
    Assert.equal(state:input_modes().application_keypad, true)
    state:apply(Actions.esc(">", ""))
    Assert.equal(state.modes.application_keypad, false)
    state:apply(Actions.esc("8", "#"))
    Assert.equal(text_at(state, 0), "EEEEEEEEEEEE")
    Assert.equal(text_at(state, 1), "EEEEEEEEEEEE")
    Assert.equal(state.cursor.column, 0)
    state:apply(Actions.csi({ 1 }, "", "", "I"))
    Assert.equal(state.cursor.column, 8)
    state:apply(Actions.csi({ 1 }, "", "", "Z"))
    Assert.equal(state.cursor.column, 0)
    state:write_codepoint("A")
    state:apply(Actions.csi({ 2 }, "", "", "b"))
    Assert.equal(text_at(state, 0):sub(1, 3), "AAA")
    state:apply(Actions.csi({ 2 }, "", "", "a"))
    Assert.equal(state.cursor.column, 5)
    state:apply(Actions.csi({ 1 }, "", "", "e"))
    Assert.equal(state.cursor.row, 1)
    state:apply(Actions.csi({}, "", "!", "p"))
    Assert.equal(text_at(state, 0):sub(1, 3), "AAA")
    Assert.equal(state.modes.autowrap, true)
    Assert.equal(state.modes.application_keypad, false)
    state:apply(Actions.csi({}, "", "", "b"))
    Assert.equal(state.stats.unknown.csi, 1)
  end,
  terminal_state_resize_preserves_the_active_screen_and_marks_full_damage = function()
    local state = State.new(4, 2)
    state:set_cell(0, 0, state:cell_from_attributes("P"))
    state:switch_alternate(true, true)
    state:set_cell(0, 0, state:cell_from_attributes("A"))
    state:resize(6, 3)
    Assert.equal(state.active_screen, state.alternate)
    Assert.equal(state:get(0, 0).glyph, "A")
    Assert.truthy(state.damage.full)
    state:switch_alternate(false, true)
    Assert.equal(state:get(0, 0).glyph, "P")
  end,
  terminal_state_skips_reflow_when_unwrapped_primary_rows_fit_the_new_width = function()
    local state = State.new(8, 1, { scrollback_limit = 2 })
    for _, glyph in ipairs({ "a", "b", "c" }) do state:write_codepoint(glyph) end
    state:carriage_return()
    state:line_feed()
    for _, glyph in ipairs({ "d", "e", "f" }) do state:write_codepoint(glyph) end
    state:carriage_return()
    state:line_feed()
    local first_line_id = state.scrollback:get(1).line_id
    Assert.truthy(state:can_keep_primary_rows_on_resize(7, 1))
    state:resize(7, 1)
    Assert.equal(state.scrollback:size(), 2)
    Assert.equal(state.scrollback:get(1).line_id, first_line_id)
    Assert.equal(state.scrollback:get(1).cells[0].glyph, "a")
    Assert.equal(state.scrollback:get(2).cells[2].glyph, "f")
    Assert.truthy(state:can_keep_primary_rows_on_resize(8, 1))
    state:resize(8, 1)
    Assert.equal(state.scrollback:get(1).cells[7].glyph, " ")
  end,
  terminal_state_reflows_when_a_width_change_also_changes_the_row_count = function()
    local state = State.new(8, 2, { scrollback_limit = 2 })
    state:write_codepoint("a")
    state:carriage_return()
    state:line_feed()
    state:write_codepoint("b")
    state:resize(7, 1)
    Assert.equal(state.scrollback:size(), 1)
    Assert.equal(state.scrollback:get(1).cells[0].glyph, "a")
    Assert.equal(state:get(0, 0).glyph, "b")
  end,
  terminal_state_reflows_primary_scrollback_selection_and_cursor_on_column_resize = function()
    local state = State.new(4, 2, { scrollback_limit = 4 })
    for _, glyph in ipairs({ "a", "b", "c", "d", "e", "f" }) do state:write_codepoint(glyph) end
    Assert.truthy(state:set_selection(0, 1, 1, 2))
    state:resize(3, 2)
    Assert.equal(text_at(state, 0), "abc")
    Assert.equal(text_at(state, 1), "def")
    Assert.equal(state:selection_text(32), "bcdef")
    Assert.equal(state.cursor.row, 1)
    Assert.equal(state.cursor.column, 2)
    Assert.truthy(state.cursor.pending_wrap)
  end,
}
