local Assert = require("tests.assert")
local Actions = require("kiwi.terminal.actions")
local Base64 = require("kiwi.terminal.base64")
local Color = require("kiwi.renderer.color")
local State = require("kiwi.terminal.state")

local function text_at(state, row)
  local characters = {}
  for column = 0, state.columns - 1 do
    characters[#characters + 1] = state:get(column, row).glyph
  end
  return table.concat(characters)
end

return {
  terminal_state_uses_deferred_autowrap = function()
    local state = State.new(3, 2)
    state.damage:clear()
    state:write_codepoint("A")
    state:write_codepoint("B")
    state:write_codepoint("C")
    Assert.equal(text_at(state, 0), "ABC")
    Assert.equal(state.cursor.column, 2)
    Assert.truthy(state.cursor.pending_wrap)
    state:write_codepoint("D")
    Assert.equal(text_at(state, 1), "D  ")
    Assert.equal(state.cursor.column, 1)
    Assert.equal(state.cursor.row, 1)
  end,
  terminal_state_scrolls_margins_without_rebuilding_other_rows = function()
    local state = State.new(4, 4)
    for row = 0, 3 do
      state:set_cell(0, row, state:cell_from_attributes(tostring(row)))
    end
    Assert.truthy(state:set_margins(2, 4))
    state:scroll_up(1)
    Assert.equal(state:get(0, 0).glyph, "0")
    Assert.equal(state:get(0, 1).glyph, "2")
    Assert.equal(state:get(0, 2).glyph, "3")
    Assert.equal(state:get(0, 3).glyph, " ")
  end,
  terminal_state_keeps_alternate_screen_out_of_primary_scrollback = function()
    local state = State.new(3, 2, { scrollback_limit = 4 })
    state:set_cell(0, 0, state:cell_from_attributes("P"))
    state:scroll_up(1)
    Assert.equal(state.scrollback:size(), 1)
    state:switch_alternate(true, true)
    state:set_cell(0, 1, state:cell_from_attributes("A"))
    state:scroll_up(1)
    Assert.equal(state.scrollback:size(), 1)
    state:switch_alternate(false, true)
    Assert.equal(state.active_screen, state.primary)
    Assert.equal(state.scrollback:size(), 1)
  end,
  terminal_state_resolves_sgr_colours_and_inverse = function()
    local state = State.new(4, 1)
    state:apply(Actions.csi({ 38, 2, 1, 2, 3, 48, 5, 12, 7 }, "", "", "m"))
    state:write_codepoint("X")
    local cell = state:get(0, 0)
    Assert.equal(cell.glyph, "X")
    Assert.truthy(cell.fg ~= cell.bg)
    Assert.truthy(cell.flags ~= 0)
    state:apply(Actions.csi({ 0 }, "", "", "m"))
    state:write_codepoint("Y")
    Assert.equal(state:get(1, 0).flags, 0)
  end,
  terminal_state_applies_and_resets_osc_palette_colours_to_existing_cells = function()
    local state = State.new(4, 1)
    state:apply(Actions.csi({ 31 }, "", "", "m"))
    state:write_codepoint("R")
    local red = state:get(0, 0)
    Assert.equal(red.fg_slot, 2)
    state:apply(Actions.osc(4, "1;#010203"))
    local changed = Color.unpack(state:get(0, 0).fg)
    Assert.equal(changed.red, 1)
    Assert.equal(changed.green, 2)
    Assert.equal(changed.blue, 3)
    state:apply(Actions.osc(4, "1;?"))
    Assert.equal(state:pop_responses()[1], "\27]4;1;rgb:0101/0202/0303\27\\")
    state:apply(Actions.osc(104, "1"))
    Assert.truthy(state:get(0, 0).fg ~= Color.pack(1, 2, 3, 0xff))
  end,
  terminal_state_applies_osc_default_colours_without_mutating_literal_rgb_cells = function()
    local state = State.new(3, 1)
    state:write_codepoint("D")
    state:apply(Actions.csi({ 38, 2, 9, 8, 7 }, "", "", "m"))
    state:write_codepoint("L")
    state:apply(Actions.osc(10, "rgb:1212/3434/5656"))
    local default = Color.unpack(state:get(0, 0).fg)
    local literal = Color.unpack(state:get(1, 0).fg)
    Assert.equal(default.red, 0x12)
    Assert.equal(default.green, 0x34)
    Assert.equal(default.blue, 0x56)
    Assert.equal(literal.red, 9)
    Assert.equal(literal.green, 8)
    Assert.equal(literal.blue, 7)
    state:apply(Actions.osc(11, "?"))
    Assert.truthy(state:pop_responses()[1]:match("^\27%]11;rgb:"))
  end,
  terminal_state_denies_osc52_unless_the_host_explicitly_enables_it = function()
    local effects = {}
    local state = State.new(4, 1, { effect_sink = function(kind, value) effects[#effects + 1] = { kind = kind, value = value } end })
    state:apply(Actions.osc(52, "c;" .. Base64.encode("clipboard text")))
    Assert.equal(effects[#effects].kind, "clipboard_write_denied")
    Assert.equal(effects[#effects].value.reason, "disabled")
    state:configure_osc52_write(true)
    state:apply(Actions.osc(52, "c;" .. Base64.encode("clipboard text")))
    Assert.equal(effects[#effects].kind, "clipboard_write_requested")
    Assert.equal(effects[#effects].value.text, "clipboard text")
    state:apply(Actions.osc(52, "c;%%%%"))
    Assert.equal(effects[#effects].kind, "clipboard_write_denied")
    Assert.equal(effects[#effects].value.reason, "invalid")
  end,
  terminal_state_emits_bounded_notification_and_progress_effects = function()
    local effects = {}
    local state = State.new(4, 1, { effect_sink = function(kind, value) effects[#effects + 1] = { kind = kind, value = value } end })
    state:apply(Actions.osc(9, "build completed"))
    Assert.equal(effects[#effects].kind, "notification_requested")
    Assert.equal(effects[#effects].value.body, "build completed")
    state:apply(Actions.osc(9, "4;1;73"))
    Assert.equal(effects[#effects].kind, "progress_changed")
    Assert.equal(effects[#effects].value.progress, 73)
    state:apply(Actions.osc(9, "4;1;101"))
    Assert.equal(state.stats.unknown.osc, 1)
  end,
  terminal_state_configures_a_complete_host_theme_without_losing_palette_sources = function()
    local state = State.new(3, 1)
    state:apply(Actions.csi({ 31 }, "", "", "m"))
    state:write_codepoint("R")
    state:configure_palette({
      foreground = Color.pack(1, 2, 3, 0xff),
      background = Color.pack(4, 5, 6, 0xff),
      palette = { [1] = Color.pack(7, 8, 9, 0xff) },
    })
    Assert.equal(state:get(0, 0).fg_slot, 2)
    Assert.equal(Color.unpack(state:get(0, 0).fg).blue, 9)
    state:apply(Actions.csi({ 0 }, "", "", "m"))
    state:write_codepoint("D")
    Assert.equal(Color.unpack(state:get(1, 0).fg).red, 1)
    Assert.equal(Color.unpack(state:get(1, 0).bg).green, 5)
  end,
  terminal_state_emits_conservative_status_responses = function()
    local state = State.new(4, 2)
    state:set_cursor(2, 1)
    state:apply(Actions.csi({ 5 }, "", "", "n"))
    state:apply(Actions.csi({ 6 }, "", "", "n"))
    state:apply(Actions.csi({}, "", "", "c"))
    local responses = state:pop_responses()
    Assert.equal(responses[1], "\27[0n")
    Assert.equal(responses[2], "\27[2;3R")
    Assert.equal(responses[3], "\27[?1;0c")
  end,
  terminal_state_models_cursor_style_across_alternate_and_reset = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 3 }, "", " ", "q"))
    Assert.equal(state.modes.cursor_style, 3)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.cursor_style, 3)
    state:apply(Actions.csi({ 6 }, "", " ", "q"))
    state:apply(Actions.csi({ 1049 }, "?", "", "l"))
    Assert.equal(state.modes.cursor_style, 6)
    state:apply(Actions.csi({ 0 }, "", " ", "q"))
    Assert.equal(state.modes.cursor_style, 1)
    state:apply(Actions.csi({ 7 }, "", " ", "q"))
    Assert.equal(state.stats.unknown.csi, 1)
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.cursor_style, 1)
  end,
  terminal_state_resets_synchronized_output_and_rejects_unknown_modes = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 2026 }, "?", "", "h"))
    state:apply(Actions.csi({ 2026 }, "?", "", "h"))
    Assert.equal(state.modes.synchronized_output, true)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.synchronized_output, true)
    state:apply(Actions.csi({ 2026 }, "?", "", "l"))
    Assert.equal(state.modes.synchronized_output, false)
    state:apply(Actions.csi({ 2027 }, "?", "", "h"))
    Assert.equal(state.stats.unknown.csi, 1)
    state:apply(Actions.csi({ 2026 }, "?", "", "h"))
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.synchronized_output, false)
  end,
  terminal_state_tracks_sgr_mouse_and_focus_modes_through_reset = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 1002, 1006, 1004 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "button")
    Assert.equal(state.modes.mouse_sgr, true)
    Assert.equal(state.modes.focus_reporting, true)
    local generation = state.modes.mouse_generation
    state:apply(Actions.csi({ 1003 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "any")
    Assert.truthy(state.modes.mouse_generation > generation)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "any")
    state:apply(Actions.csi({ 1049 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_sgr, true)
    state:apply(Actions.csi({ 1002 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "any")
    state:apply(Actions.csi({ 1003, 1006 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "none")
    Assert.equal(state.modes.mouse_sgr, false)
    state:apply(Actions.csi({ 1000, 1002 }, "?", "", "h"))
    Assert.equal(state.modes.mouse_tracking, "button")
    state:apply(Actions.csi({ 1002 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "normal")
    state:apply(Actions.csi({ 1000 }, "?", "", "l"))
    Assert.equal(state.modes.mouse_tracking, "none")
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.focus_reporting, false)
  end,
  terminal_state_negotiates_bounded_kitty_keyboard_disambiguation = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({}, "?", "", "u"))
    Assert.equal(state:pop_responses()[1], "\27[?0u")
    state:apply(Actions.csi({ 1 }, ">", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 1)
    state:apply(Actions.csi({ 1049 }, "?", "", "h"))
    Assert.equal(state.modes.keyboard_flags, 0)
    state:apply(Actions.csi({ 1 }, ">", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 1)
    state:apply(Actions.csi({}, "<", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 0)
    state:apply(Actions.csi({ 1049 }, "?", "", "l"))
    Assert.equal(state.modes.keyboard_flags, 1)
    state:apply(Actions.csi({}, "<", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 0)
    state:apply(Actions.csi({ 1, 4 }, "=", "", "u"))
    Assert.equal(state.stats.unknown.csi, 1)
    state:apply(Actions.esc("c"))
    Assert.equal(state.modes.keyboard_flags, 0)
    for index = 1, 9 do
      state:apply(Actions.csi({ index % 2 }, ">", "", "u"))
    end
    Assert.equal(#state.active_screen.keyboard_stack, 8)
  end,
  terminal_state_negotiates_all_kitty_keyboard_progressive_enhancement_flags = function()
    local state = State.new(4, 2)
    state:apply(Actions.csi({ 31 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 11)
    state:apply(Actions.csi({ 6 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 2)
    state:apply(Actions.csi({ 9, 2 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 11)
    state:apply(Actions.csi({ 8, 3 }, "=", "", "u"))
    Assert.equal(state.modes.keyboard_flags, 3)
    state:apply(Actions.csi({}, "?", "", "u"))
    Assert.equal(state:pop_responses()[1], "\27[?3u")
  end,
  terminal_state_handles_xterm_alignment_keypad_soft_reset_tabs_and_repeat = function()
    local state = State.new(12, 2)
    state:apply(Actions.esc("=", ""))
    Assert.equal(state.modes.application_keypad, true)
    state:apply(Actions.esc(">", ""))
    Assert.equal(state.modes.application_keypad, false)
    state:apply(Actions.esc("8", "#"))
    Assert.equal(text_at(state, 0), "EEEEEEEEEEEE")
    Assert.equal(text_at(state, 1), "EEEEEEEEEEEE")
    Assert.equal(state.cursor.column, 0)
    state:apply(Actions.csi({ 1 }, "", "", "I"))
    Assert.equal(state.cursor.column, 8)
    state:apply(Actions.csi({ 1 }, "", "", "Z"))
    Assert.equal(state.cursor.column, 0)
    state:write_codepoint("A")
    state:apply(Actions.csi({ 2 }, "", "", "b"))
    Assert.equal(text_at(state, 0):sub(1, 3), "AAA")
    state:apply(Actions.csi({ 2 }, "", "", "a"))
    Assert.equal(state.cursor.column, 5)
    state:apply(Actions.csi({ 1 }, "", "", "e"))
    Assert.equal(state.cursor.row, 1)
    state:apply(Actions.csi({}, "!", "", "p"))
    Assert.equal(text_at(state, 0):sub(1, 3), "AAA")
    Assert.equal(state.modes.autowrap, true)
    Assert.equal(state.modes.application_keypad, false)
    state:apply(Actions.csi({}, "", "", "b"))
    Assert.equal(state.stats.unknown.csi, 1)
  end,
  terminal_state_resize_preserves_the_active_screen_and_marks_full_damage = function()
    local state = State.new(4, 2)
    state:set_cell(0, 0, state:cell_from_attributes("P"))
    state:switch_alternate(true, true)
    state:set_cell(0, 0, state:cell_from_attributes("A"))
    state:resize(6, 3)
    Assert.equal(state.active_screen, state.alternate)
    Assert.equal(state:get(0, 0).glyph, "A")
    Assert.truthy(state.damage.full)
    state:switch_alternate(false, true)
    Assert.equal(state:get(0, 0).glyph, "P")
  end,
  terminal_state_reflows_primary_scrollback_selection_and_cursor_on_column_resize = function()
    local state = State.new(4, 2, { scrollback_limit = 4 })
    for _, glyph in ipairs({ "a", "b", "c", "d", "e", "f" }) do state:write_codepoint(glyph) end
    Assert.truthy(state:set_selection(0, 1, 1, 2))
    state:resize(3, 2)
    Assert.equal(text_at(state, 0), "abc")
    Assert.equal(text_at(state, 1), "def")
    Assert.equal(state:selection_text(32), "bcdef")
    Assert.equal(state.cursor.row, 1)
    Assert.equal(state.cursor.column, 2)
    Assert.truthy(state.cursor.pending_wrap)
  end,
}
