local Assert = require("tests.assert")
local Backend = require("kiwi.text.backend")
local State = require("kiwi.terminal.state")
local System = require("kiwi.font.system")
local Utf8 = require("kiwi.terminal.utf8")

local function text_system()
  return System.new({ pixel_height = 18, atlas = { width = 512, height = 512, max_entries = 1024 } })
end

local function write(state, codepoint)
  state:write_codepoint(Utf8.encode(codepoint), codepoint)
end

return {
  text_backend_declares_stable_semantic_contract = function()
    local system = text_system()
    local backend = Backend.create(system)
    local descriptor = backend:descriptor()
    Assert.equal(descriptor.abi_version, 1)
    Assert.equal(descriptor.requested, "atlas")
    Assert.equal(descriptor.active, "atlas")
    Assert.equal(descriptor.fallback, false)
    Assert.equal(descriptor.capabilities.terminal_layout_authority, "kiwi")
    Assert.equal(descriptor.capabilities.glyph_output, "text.shaped_glyphs")
    Assert.equal(descriptor.capabilities.gpu_resource, "text.alpha_atlas")
    backend:destroy()
    system:destroy()
  end,
  text_backend_falls_back_to_the_atlas_adapter_without_changing_layout = function()
    local baseline_system = text_system()
    local fallback_system = text_system()
    local baseline = Backend.create(baseline_system, { requested = "atlas" })
    local fallback = Backend.create(fallback_system, { requested = "msdf" })
    local state = State.new(8, 1)
    write(state, string.byte("A"))
    write(state, 0x4e2d)
    local baseline_glyphs = baseline:update(state)
    local fallback_glyphs = fallback:update(state)
    local descriptor = fallback:descriptor()
    Assert.equal(descriptor.requested, "msdf")
    Assert.equal(descriptor.active, "atlas")
    Assert.equal(descriptor.fallback, true)
    Assert.equal(descriptor.fallback_reason, "unsupported-backend")
    Assert.equal(state:get(1, 0).width, 2)
    Assert.equal(#fallback_glyphs, #baseline_glyphs)
    fallback:destroy()
    baseline:destroy()
    fallback_system:destroy()
    baseline_system:destroy()
  end,
  text_backend_rejects_invalid_selection_and_use_after_destroy = function()
    local system = text_system()
    local invalid = pcall(function() Backend.create(system, { requested = 1 }) end)
    Assert.equal(invalid, false)
    local oversized = pcall(function() Backend.create(system, { requested = string.rep("a", 65) }) end)
    Assert.equal(oversized, false)
    local backend = Backend.create(system)
    backend:destroy()
    local usable = pcall(function() backend:layout() end)
    Assert.equal(usable, false)
    system:destroy()
  end,
}
