local Assert = require("tests.assert")
local Base64 = require("kiwi.terminal.base64")
local Parser = require("kiwi.terminal.parser")
local Replay = require("kiwi.terminal.replay")
local Snapshot = require("kiwi.terminal.snapshot")
local State = require("kiwi.terminal.state")

local LIVE_RECORDING = "src/tests/fixtures/replay/live-color-cr.jsonl"
local UNICODE_RECORDING = "src/tests/fixtures/replay/unicode-clusters.jsonl"
local RIGHT_MARGIN_UNICODE_RECORDING = "src/tests/fixtures/replay/unicode-right-margin.jsonl"
local KITTY_PLACEMENT_RECORDING = "src/tests/fixtures/replay/kitty-placement.jsonl"

local function with_temporary_recording(callback)
  local path = os.tmpname()
  local ok, result = xpcall(function()
    return callback(path)
  end, debug.traceback)
  os.remove(path)
  if not ok then
    error(result)
  end
  return result
end

return {
  base64_round_trips_terminal_bytes = function()
    local bytes = "\0\27[31m€\255"
    Assert.equal(Base64.decode(Base64.encode(bytes)), bytes)
  end,
  recording_replay_matches_direct_parser_state = function()
    with_temporary_recording(function(path)
      local recording = Replay.Recorder.new(path)
      recording:resize(7, 3)
      recording:output("\27[31mred\27[0m\rX\n")
      recording:output("€")
      recording:close()

      local replayed = State.new(1, 1)
      local stats = Replay.apply_file(replayed, path)
      local direct = State.new(7, 3)
      local parser = Parser.new(function(action)
        direct:apply(action)
      end)
      parser:feed("\27[31mred\27[0m\rX\n€")
      parser:finish()
      Assert.equal(Snapshot.encode(replayed), Snapshot.encode(direct))
      Assert.equal(stats.bytes, #"\27[31mred\27[0m\rX\n€")
    end)
  end,
  replay_preserves_recorded_cell_metrics_for_pixel_geometry_queries = function()
    with_temporary_recording(function(path)
      local recording = Replay.Recorder.new(path)
      recording:resize(7, 3, 9, 17)
      recording:output("\27[14t\27[16t")
      recording:close()

      local replayed = State.new(1, 1)
      local stats = Replay.apply_file(replayed, path)
      Assert.equal(replayed.cell_width, 9)
      Assert.equal(replayed.cell_height, 17)
      local responses = replayed:pop_responses()
      Assert.equal(#responses, 2)
      Assert.equal(responses[1], "\27[4;51;63t")
      Assert.equal(responses[2], "\27[6;17;9t")
      Assert.equal(replayed.stats.unknown.csi, 0)
      Assert.equal(stats.errors, 0)
    end)
  end,
  recording_replay_is_invariant_under_adversarial_output_chunking = function()
    with_temporary_recording(function(path)
      local recording = Replay.Recorder.new(path)
      recording:resize(7, 3)
      recording:output("\27[31mred\27[")
      recording:output("0m\rX\n\226")
      recording:output("\130\172\27]2;title\27\\")
      recording:close()
      local state, stats, seeds = Replay.verify_chunk_invariance(path)
      Assert.equal(state.title, "title")
      Assert.equal(state:get(0, 0).glyph, "X")
      Assert.equal(state:get(1, 1).glyph, "€")
      Assert.equal(stats.errors, 0)
      Assert.equal(seeds, 8)
    end)
  end,
  replay_preserves_mouse_and_focus_modes_across_the_alternate_screen = function()
    with_temporary_recording(function(path)
      local recording = Replay.Recorder.new(path)
      recording:resize(4, 2)
      recording:output("\27[?1002;1006;1004h\27[?1049h\27[?1049l")
      recording:close()

      local replayed = State.new(1, 1)
      local stats = Replay.apply_file(replayed, path)
      Assert.equal(replayed.modes.mouse_tracking, "button")
      Assert.equal(replayed.modes.mouse_sgr, true)
      Assert.equal(replayed.modes.focus_reporting, true)
      Assert.equal(replayed.active_screen, replayed.primary)
      Assert.equal(stats.errors, 0)
    end)
  end,
  replay_rejects_unsupported_versions = function()
    with_temporary_recording(function(path)
      local file = assert(io.open(path, "wb"))
      file:write('{"data":"QQ==","event":"output","v":2}\n')
      file:close()
      local state = State.new(2, 1)
      local ok = pcall(Replay.apply_file, state, path)
      Assert.equal(ok, false)
    end)
  end,
  live_recording_fixture_replays_to_expected_cells = function()
    local state = State.new(1, 1)
    local stats = Replay.apply_file(state, LIVE_RECORDING)
    Assert.equal(state.columns, 133)
    Assert.equal(state.rows, 40)
    Assert.equal(state:get(0, 0).glyph, "X")
    Assert.equal(state:get(1, 0).glyph, "e")
    Assert.equal(state:get(0, 0).fg, state:get(6, 0).fg)
    Assert.truthy(state:get(1, 0).fg ~= state:get(6, 0).fg)
    Assert.equal(stats.bytes, 18)
    Assert.equal(stats.errors, 0)
  end,
  unicode_replay_preserves_split_clusters_and_wide_occupancy = function()
    local state = State.new(1, 1)
    local stats = Replay.apply_file(state, UNICODE_RECORDING)
    Assert.equal(state:get(0, 0).glyph, "e\204\129")
    Assert.equal(state:get(0, 0).width, 1)
    Assert.equal(state:get(1, 0).width, 2)
    Assert.truthy(state:get(2, 0).continuation)
    Assert.equal(state:get(3, 0).width, 2)
    Assert.truthy(state:get(4, 0).continuation)
    Assert.equal(stats.errors, 0)
  end,
  unicode_replay_preserves_width_changing_right_margin_wrap = function()
    local state = State.new(1, 1)
    local stats = Replay.apply_file(state, RIGHT_MARGIN_UNICODE_RECORDING)
    Assert.equal(state:get(0, 0).glyph, "A")
    Assert.equal(state:get(1, 0).glyph, "\226\157\164\239\184\143")
    Assert.equal(state:get(1, 0).width, 2)
    Assert.truthy(state:get(2, 0).continuation)
    Assert.equal(state:get(0, 1).glyph, "B")
    Assert.equal(stats.errors, 0)
  end,
  kitty_placement_replay_preserves_the_bounded_cell_anchor = function()
    local state = State.new(1, 1)
    local stats = Replay.apply_file(state, KITTY_PLACEMENT_RECORDING)
    local placement = state:kitty_placements_view().placements[1]
    Assert.equal(state.columns, 4)
    Assert.equal(state.rows, 2)
    Assert.equal(placement.image_id, 1)
    Assert.equal(placement.placement_id, 5)
    Assert.equal(placement.columns, 2)
    Assert.equal(placement.rows[1].row, 0)
    Assert.equal(placement.z, -1)
    Assert.equal(stats.errors, 0)
  end,
}
