local Assert = require("tests.assert")
local PreparedFrame = require("kiwi.renderer.prepared_frame")
local State = require("kiwi.terminal.state")
local System = require("kiwi.font.system")

local function text_system()
  return System.new({ pixel_height = 18, atlas = { width = 512, height = 512, max_entries = 1024 } })
end

return {
  prepared_frame_keeps_terminal_updates_pending_until_a_backend_acknowledges_them = function()
    local font = text_system()
    local state = State.new(8, 2)
    state:write_codepoint("K")
    local prepared = PreparedFrame.new(font, state)
    local plan = prepared:prepare_model(state)
    Assert.equal(plan.revision, 1)
    Assert.equal(#plan.cell_updates, 1)
    Assert.truthy(plan.cell_updates[1].data ~= nil)
    Assert.truthy(plan.glyph_update ~= nil)
    Assert.truthy(plan.atlas_update ~= nil)
    Assert.truthy(state.damage.dirty_count > 0)
    Assert.equal(plan.descriptors.cursor.column, state.cursor.column)
    prepared:commit_model(plan)
    Assert.equal(state.damage.dirty_count, 0)
    Assert.equal(prepared.glyph_count, plan.glyph_update.count)
    Assert.equal(prepared.atlas_generation, plan.atlas_update.generation)
    prepared:destroy()
    font:destroy()
  end,
  prepared_frame_builds_backend_neutral_uniform_data = function()
    local font = text_system()
    local state = State.new(8, 2)
    local prepared = PreparedFrame.new(font, state, { command_region_visual_enabled = true })
    local frame = prepared:prepare_frame(state, 12.5, true, false, { surface_is_srgb = true })
    Assert.equal(frame.byte_count, 688)
    Assert.equal(frame.time, 12.5)
    Assert.equal(frame.delta, 12.5)
    Assert.equal(frame.data[0].columns, 8)
    Assert.equal(frame.data[0].rows, 2)
    Assert.equal(frame.data[0].show_dirty, 1)
    Assert.equal(frame.data[0].show_boundaries, 0)
    Assert.equal(frame.data[0].command_region_padding[0], 1)
    prepared:destroy()
    font:destroy()
  end,
  prepared_frame_retries_a_discarded_upload_as_a_complete_resource_snapshot = function()
    local font = text_system()
    local state = State.new(8, 2)
    local prepared = PreparedFrame.new(font, state)
    local initial = prepared:prepare_model(state)
    prepared:discard_model(initial)
    Assert.truthy(state.damage.dirty_count > 0)
    local retry = prepared:prepare_model(state)
    Assert.equal(#retry.cell_updates, 1)
    Assert.equal(retry.cell_updates[1].cell_count, 16)
    Assert.truthy(retry.glyph_update ~= nil)
    Assert.truthy(retry.atlas_update ~= nil)
    prepared:commit_model(retry)
    Assert.equal(state.damage.dirty_count, 0)
    prepared:destroy()
    font:destroy()
  end,
}
