local Window = require("kiwi.platform.window")
local Context = require("kiwi.gpu.context")
local Synthetic = require("kiwi.terminal.synthetic")
local FreeType = require("kiwi.font.freetype")
local Renderer = require("kiwi.renderer.renderer")

local window = Window.new(1280, 800, "Kiwi M0 renderer laboratory")
local context = Context.new(window)
local model = Synthetic.new(0x4b495749, 160, 50)
local font = FreeType.rasterize()
local renderer = Renderer.new(context, font, model)
local rendered, reason = renderer:render(model, window:time(), false, false)
print("rendered=" .. tostring(rendered) .. " reason=" .. tostring(reason))
renderer:destroy()
context:destroy()
window:destroy()
