#!/usr/bin/env zsh
set -euo pipefail

if [[ ${+COLORTERM} -eq 1 ]]; then
  colorterm=$COLORTERM
else
  colorterm=unset
fi

print -r -- "Kiwi truecolour contract TERM=${TERM-unknown} COLORTERM=$colorterm colors=$(tput colors)"
tput setrgbf 1 2 3
print -rn -- 'RGB 1,2,3'
tput sgr0
print
