/* Generated by wayland-scanner 1.25.0 from stable/viewporter/viewporter.xml.
 *
 * Copyright © 2013-2016 Collabora, Ltd.
 * SPDX-License-Identifier: MIT
 */

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <wayland-util.h>

#ifndef __has_attribute
#define __has_attribute(x) 0
#endif

#if __has_attribute(visibility) || (defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface wp_viewport_interface;

static const struct wl_interface *viewporter_types[] = {
  NULL, NULL, NULL, NULL, &wp_viewport_interface, &wl_surface_interface,
};

static const struct wl_message wp_viewporter_requests[] = {
  {"destroy", "", viewporter_types},
  {"get_viewport", "no", viewporter_types + 4},
};

WL_PRIVATE const struct wl_interface wp_viewporter_interface = {
  "wp_viewporter", 1, 2, wp_viewporter_requests, 0, NULL,
};

static const struct wl_message wp_viewport_requests[] = {
  {"destroy", "", viewporter_types},
  {"set_source", "ffff", viewporter_types},
  {"set_destination", "ii", viewporter_types},
};

WL_PRIVATE const struct wl_interface wp_viewport_interface = {
  "wp_viewport", 1, 3, wp_viewport_requests, 0, NULL,
};
