/* Generated by wayland-scanner 1.25.0 from stable/viewporter/viewporter.xml.
 *
 * Copyright © 2013-2016 Collabora, Ltd.
 * SPDX-License-Identifier: MIT
 */

#ifndef KIWI_VIEWPORTER_CLIENT_PROTOCOL_H
#define KIWI_VIEWPORTER_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <wayland-client.h>

struct wp_viewporter;
struct wp_viewport;

extern const struct wl_interface wp_viewporter_interface;
extern const struct wl_interface wp_viewport_interface;

enum wp_viewporter_error {
  WP_VIEWPORTER_ERROR_VIEWPORT_EXISTS = 0,
};

enum wp_viewport_error {
  WP_VIEWPORT_ERROR_BAD_VALUE = 0,
  WP_VIEWPORT_ERROR_BAD_SIZE = 1,
  WP_VIEWPORT_ERROR_OUT_OF_BUFFER = 2,
  WP_VIEWPORT_ERROR_NO_SURFACE = 3,
};

enum {
  WP_VIEWPORTER_DESTROY,
  WP_VIEWPORTER_GET_VIEWPORT,
};

enum {
  WP_VIEWPORT_DESTROY,
  WP_VIEWPORT_SET_SOURCE,
  WP_VIEWPORT_SET_DESTINATION,
};

static inline void wp_viewporter_destroy(struct wp_viewporter *viewporter) {
  wl_proxy_marshal_flags((struct wl_proxy *)viewporter, WP_VIEWPORTER_DESTROY, NULL,
                         wl_proxy_get_version((struct wl_proxy *)viewporter),
                         WL_MARSHAL_FLAG_DESTROY);
}

static inline struct wp_viewport *wp_viewporter_get_viewport(
    struct wp_viewporter *viewporter, struct wl_surface *surface) {
  return (struct wp_viewport *)wl_proxy_marshal_flags(
      (struct wl_proxy *)viewporter, WP_VIEWPORTER_GET_VIEWPORT,
      &wp_viewport_interface, wl_proxy_get_version((struct wl_proxy *)viewporter), 0,
      NULL, surface);
}

static inline void wp_viewport_destroy(struct wp_viewport *viewport) {
  wl_proxy_marshal_flags((struct wl_proxy *)viewport, WP_VIEWPORT_DESTROY, NULL,
                         wl_proxy_get_version((struct wl_proxy *)viewport),
                         WL_MARSHAL_FLAG_DESTROY);
}

static inline void wp_viewport_set_source(struct wp_viewport *viewport,
                                          wl_fixed_t x, wl_fixed_t y,
                                          wl_fixed_t width, wl_fixed_t height) {
  wl_proxy_marshal_flags((struct wl_proxy *)viewport, WP_VIEWPORT_SET_SOURCE, NULL,
                         wl_proxy_get_version((struct wl_proxy *)viewport), 0,
                         x, y, width, height);
}

static inline void wp_viewport_set_destination(struct wp_viewport *viewport,
                                               int32_t width, int32_t height) {
  wl_proxy_marshal_flags((struct wl_proxy *)viewport, WP_VIEWPORT_SET_DESTINATION,
                         NULL, wl_proxy_get_version((struct wl_proxy *)viewport), 0,
                         width, height);
}

#endif
