local GtkWindow = require("kiwi.platform.gtk_window")

assert(GtkWindow.bridge ~= nil, "GTK host bridge was not loaded")
assert(GtkWindow.bridge.kiwi_gtk_host_abi_version() == 4, "GTK host input ABI is unavailable or incompatible")
assert(type(GtkWindow.bridge.kiwi_gtk_host_new) == "cdata", "GTK host constructor ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_keyboard_supported_flags) == "cdata", "GTK keyboard-capability ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_key_variants_inject_smoke) == "cdata", "GTK key-variant smoke ABI is unavailable")
assert(GtkWindow.bridge.kiwi_gtk_host_pc101_base_key(38) == string.byte("a"), "GTK PC-101 A mapping is unavailable")
assert(GtkWindow.bridge.kiwi_gtk_host_pc101_base_key(24) == string.byte("q"), "GTK PC-101 Q mapping is unavailable")
assert(GtkWindow.bridge.kiwi_gtk_host_pc101_base_key(0) == 0, "GTK PC-101 mapping has an invalid fallback")
assert(type(GtkWindow.bridge.kiwi_gtk_host_create_surface) == "cdata", "GTK host surface ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_set_text_input_caret) == "cdata", "GTK text-input caret ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_terminal_presentation_set_pointer_shape) == "cdata", "GTK pointer-shape ABI is unavailable")
assert(GtkWindow.bridge.kiwi_gtk_gl_renderer_abi_version() == 3, "GTK GL renderer ABI is unavailable or incompatible")
assert(type(GtkWindow.bridge.kiwi_gtk_host_enable_gl_area_probe) == "cdata", "GTK GL area probe ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_native_tab_probe) == "cdata", "GTK native-tab probe ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_native_tab_count) == "cdata", "GTK native-tab count ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_request_gl_area_render) == "cdata", "GTK GL area render ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_gl_area_state) == "cdata", "GTK GL area state ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_gl_area_rendered_revision) == "cdata", "GTK GL renderer revision ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_gl_area_upload_metrics) == "cdata", "GTK GL renderer metrics ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_gl_area_submit_snapshot) == "cdata", "GTK GL snapshot ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_notify) == "cdata", "GTK notification ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_text_input_inject_smoke) == "cdata", "GTK text-input smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_key_text_inject_smoke) == "cdata", "GTK key/text smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_set_product_action_handler) == "cdata", "GTK product-action ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_product_action_invoke_smoke) == "cdata", "GTK product-menu smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_open_text_file) == "cdata", "GTK text-file opener ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_command_palette_show) == "cdata", "GTK command-palette ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_command_palette_invoke_smoke) == "cdata", "GTK command-palette smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_accessibility_update) == "cdata", "GTK accessibility ABI is unavailable")
print("GTK host ABI check passed.")
