local GtkWindow = require("kiwi.platform.gtk_window")

assert(GtkWindow.bridge ~= nil, "GTK host bridge was not loaded")
assert(type(GtkWindow.bridge.kiwi_gtk_host_new) == "cdata", "GTK host constructor ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_create_surface) == "cdata", "GTK host surface ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_set_text_input_caret) == "cdata", "GTK text-input caret ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_text_input_inject_smoke) == "cdata", "GTK text-input smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_key_text_inject_smoke) == "cdata", "GTK key/text smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_accessibility_update) == "cdata", "GTK accessibility ABI is unavailable")
print("GTK host ABI check passed.")
