local GtkWindow = require("kiwi.platform.gtk_window")

assert(GtkWindow.bridge ~= nil, "GTK host bridge was not loaded")
assert(type(GtkWindow.bridge.kiwi_gtk_host_new) == "cdata", "GTK host constructor ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_create_surface) == "cdata", "GTK host surface ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_set_text_input_caret) == "cdata", "GTK text-input caret ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_enable_gl_area_probe) == "cdata", "GTK GL area probe ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_request_gl_area_render) == "cdata", "GTK GL area render ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_gl_area_state) == "cdata", "GTK GL area state ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_notify) == "cdata", "GTK notification ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_text_input_inject_smoke) == "cdata", "GTK text-input smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_key_text_inject_smoke) == "cdata", "GTK key/text smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_set_product_action_handler) == "cdata", "GTK product-action ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_product_action_invoke_smoke) == "cdata", "GTK product-menu smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_open_text_file) == "cdata", "GTK text-file opener ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_command_palette_show) == "cdata", "GTK command-palette ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_command_palette_invoke_smoke) == "cdata", "GTK command-palette smoke ABI is unavailable")
assert(type(GtkWindow.bridge.kiwi_gtk_host_accessibility_update) == "cdata", "GTK accessibility ABI is unavailable")
print("GTK host ABI check passed.")
