local tests = {
  require("tests.test_damage"),
  require("tests.test_build"),
  require("tests.test_doctor"),
  require("tests.test_paths"),
  require("tests.test_config"),
  require("tests.test_workspace"),
  require("tests.test_terminal"),
  require("tests.test_synthetic"),
  require("tests.test_utf8"),
  require("tests.test_unicode"),
  require("tests.test_state"),
  require("tests.test_text_state"),
  require("tests.test_text_fixtures"),
  require("tests.test_text_layout"),
  require("tests.test_text_backend"),
  require("tests.test_text_lab"),
  require("tests.test_accessibility"),
  require("tests.test_harfbuzz_diff"),
  require("tests.test_parser"),
  require("tests.test_vt_terminal"),
  require("tests.test_kitty_graphics"),
  require("tests.test_animated_images"),
  require("tests.test_kitty_placements"),
  require("tests.test_kitty_image_script"),
  require("tests.test_kitty_image_renderer"),
  require("tests.test_fuzz"),
  require("tests.test_replay"),
  require("tests.test_reflow"),
  require("tests.test_diagnostics"),
  require("tests.test_conformance"),
  require("tests.test_parser_bench"),
  require("tests.test_pipeline_bench"),
  require("tests.test_longrun"),
  require("tests.test_pacing"),
  require("tests.test_power"),
  require("tests.test_device_soak"),
  require("tests.test_text_bench"),
  require("tests.test_write_bench"),
  require("tests.test_glyph_fallback"),
  require("tests.test_keyboard"),
  require("tests.test_mouse"),
  require("tests.test_selection"),
  require("tests.test_selection_pointer"),
  require("tests.test_selection_renderer"),
  require("tests.test_clipboard"),
  require("tests.test_hyperlink"),
  require("tests.test_shell_integration"),
  require("tests.test_shell_scripts"),
  require("tests.test_command_regions"),
  require("tests.test_command_region_retention"),
  require("tests.test_command_region_navigation"),
  require("tests.test_command_region_renderer"),
  require("tests.test_command_region_extension_sample"),
  require("tests.test_composition_spike"),
  require("tests.test_search"),
  require("tests.test_search_renderer"),
  require("tests.test_atlas"),
  require("tests.test_freetype"),
  require("tests.test_glyph_shader"),
  require("tests.test_packing"),
  require("tests.test_pass_registry"),
  require("tests.test_pass_api"),
  require("tests.test_extensions"),
  require("tests.test_extension_sample"),
  require("tests.test_pass_metrics"),
  require("tests.test_pass_budgets"),
  require("tests.test_invalidation"),
  require("tests.test_inspector"),
  require("tests.test_gpu_timing"),
  require("tests.test_gpu_recovery"),
  require("tests.test_timestamp_probe"),
  require("tests.test_renderer_resources"),
  require("tests.test_shader_loader"),
  require("tests.test_shader_reloader"),
  require("tests.test_color"),
  require("tests.test_json"),
  require("tests.test_stats"),
}

local total = 0
for _, suite in ipairs(tests) do
  for name, test in pairs(suite) do
    total = total + 1
    local ok, err = xpcall(test, debug.traceback)
    if not ok then
      io.stderr:write("FAIL ", name, "\n", err, "\n")
      os.exit(1)
    end
    io.stdout:write("PASS ", name, "\n")
  end
end

io.stdout:write(string.format("%d deterministic LuaJIT tests passed.\n", total))
